SELECT C.NAME AS COLUMN_NAME, 
       S.NAME AS DATA_TYPE, 
       C.IS_IDENTITY,
	   C.COLUMN_ID
FROM SYS.TABLES AS T 
JOIN SYS.COLUMNS AS C 
ON T.OBJECT_ID = C.OBJECT_ID 
JOIN SYS.TYPES AS S 
ON C.USER_TYPE_ID = S.USER_TYPE_ID 
LEFT OUTER JOIN SYS.DEFAULT_CONSTRAINTS AS D 
ON C.OBJECT_ID = D.PARENT_OBJECT_ID 
AND C.COLUMN_ID = D.PARENT_COLUMN_ID
WHERE T.TYPE = 'U' AND T.NAME = @NAME