INSERT INTO INFM_PESSOACRM
           (IDPESSOACRM
           ,IDCRM
          ,DTHPROXAGENDAMENTO
		   ,DESAGENDAMENTO
		   ,IDGRUPOCOMPROMISSO
		   ,DTHPROXAGENDAMENTOFIN
		   ,BOLCONCLUIDO)
     VALUES
           (@IDPESSOACRM
           ,@IDCRM
           ,@DTHPROXAGENDAMENTO
		   ,@DESAGENDAMENTO
		   ,@IDGRUPOCOMPROMISSO
		   ,@DTHPROXAGENDAMENTOFIN
		   ,@BOLCONCLUIDO)