SELECT D.IDDOCUMENTO
      ,D.IDFILIAL
      ,D.IDPESSOA
      ,D.IDTIPODOCUMENTO
      ,D.IDLOCALDOCUMENTO
      ,D.IDFORMAPAGAMENTO
      ,D.IDADMINISTRADORA
      ,D.IDDOCUMENTOPAI
      ,D.CODTRANSACAO
      ,D.DESNUMBOLETOBANCARIO
      ,D.DTHEMISSAO
      ,D.DTHVENCORIGINAL
      ,D.DTHVENCATUAL
      ,D.NUMVALORORIGINAL
      ,D.BOLPARCELADO
      ,D.OBSDOCUMENTO
      ,D.CODDOCUMENTO
  FROM INFM_DOCUMENTO AS D
  INNER JOIN INFM_FILIAL AS F ON F.IDFILIAL = D.IDFILIAL
  INNER JOIN INFM_EMPRESA AS E ON E.IDEMPRESA = F.IDEMPRESA
  WHERE E.IDEMPRESA = @IDEMPRESA