SELECT E.IDEMPRESA,
	   E.CODEMPRESA,
	   E.DESEMPRESA,
	   E.CODACESSO,
	   E.DESCNPJ,
	   E.DESINSCRICAOESTADUAL,
	   E.CODLICENCA,
	   E.NUMQUANTIDADESESSOES,
	   E.NUMQUANTIDADEACESSADA,
	   E.NUMQUANTIDADEACESSO,
	   E.SESSOSILIMITADAS,
	   E.VALIDADEILIMITADA,
	   E.BOLEMPRESAMESTE,
	   F.IDFILIAL,
	   F.CODFILIAL,
	   F.DESFILIAL,
	   F.NUMENDERECO,
	   F.DESTELEFONEFIXO,
	   F.DESTELEFONEFAX,
	   F.DESTELEFONECEL,
	   F.DESEMAIL,
	   F.IDENDERECO
FROM INFM_FILIALPESSOA FP
INNER JOIN INFM_FILIAL F ON F.IDFILIAL = FP.IDFILIAL
INNER JOIN INFM_EMPRESA E ON E.IDEMPRESA = F.IDEMPRESA
WHERE FP.IDPESSOA = @IDPESSOA
ORDER BY E.IDEMPRESA, F.IDFILIAL