UPDATE INFM_EMPRESA
   SET DESEMPRESA = @DESEMPRESA
      ,DESCNPJ = @DESCNPJ
      ,DESINSCRICAOESTADUAL = @DESINSCRICAOESTADUAL
	  ,DESEMAIL = @DESEMAIL
      ,DESSENHA = @DESSENHA
	  ,DESSMTP = @DESSMTP
      ,CODPORTA = @CODPORTA
      ,BOLSSL  = @BOLSSL
 WHERE IDEMPRESA = @IDEMPRESA