UPDATE INFM_EMPRESA
   SET CODACESSO = @CODACESSO
      ,CODLICENCA = @CODLICENCA
      ,NUMQUANTIDADESESSOES = @NUMQUANTIDADESESSOES
      ,NUMQUANTIDADEACESSADA = @NUMQUANTIDADEACESSADA
      ,NUMQUANTIDADEACESSO = @NUMQUANTIDADEACESSO
      ,SESSOSILIMITADAS = @SESSOSILIMITADAS
	  ,VALIDADEILIMITADA = @VALIDADEILIMITADA
 WHERE IDEMPRESA = @IDEMPRESA