SELECT E.IDEMPRESA,
	   E.CODEMPRESA,
	   E.DESEMPRESA,
	   E.CODACESSO,
	   E.DESCNPJ,
	   E.DESINSCRICAOESTADUAL,
	   E.CODLICENCA,
	   E.NUMQUANTIDADESESSOES,
	   E.NUMQUANTIDADEACESSADA,
	   E.NUMQUANTIDADEACESSO,
	   E.SESSOSILIMITADAS,
	   E.VALIDADEILIMITADA
FROM INFM_EMPRESA E
WHERE E.IDEMPRESA = @IDEMPRESA