SELECT F.IDFILIAL,
       F.CODFILIAL,
	   F.DESFILIAL
FROM INFM_FILIALPESSOA AS FP
INNER JOIN INFM_PESSOA AS P ON P.IDPESSOA = FP.IDPESSOA
INNER JOIN INFM_FILIAL F ON F.IDFILIAL = FP.IDFILIAL
WHERE P.IDPESSOA = @IDPESSOA