INSERT INTO INFM_FILIAL
           (IDFILIAL
           ,IDEMPRESA
           ,IDENDERECO
           ,IDPESSOA
           ,DESFILIAL
           ,BOLMATRIZ
           ,NUMENDERECO
           ,DESCOMPENDERECO
           ,DESPONTREFENDERECO
           ,DTHABERTURA
           ,DESTELEFONEFIXO
           ,DESTELEFONEFAX
           ,DESTELEFONECEL
           ,OBSFILIAL
           ,DESEMAIL
           ,NUMPISPER
           ,NUMCONFINSPER
           ,NUMOUTDESPPER
           ,NUMCONTSOCPER
           ,CODTABMERCADORIA
		   ,BOLATIVA)
     VALUES
           (@IDFILIAL
           ,@IDEMPRESA
           ,@IDENDERECO
           ,@IDPESSOA
           ,@DESFILIAL
           ,@BOLMATRIZ
           ,@NUMENDERECO
           ,@DESCOMPENDERECO
           ,@DESPONTREFENDERECO
           ,@DTHABERTURA
           ,@DESTELEFONEFIXO
           ,@DESTELEFONEFAX
           ,@DESTELEFONECEL
           ,@OBSFILIAL
           ,@DESEMAIL
           ,@NUMPISPER
           ,@NUMCONFINSPER
           ,@NUMOUTDESPPER
           ,@NUMCONTSOCPER
           ,@CODTABMERCADORIA
		   ,@BOLATIVA)