INSERT INTO INFM_GRUPOCOMPROMISSOSUBGRUPO
           (IDGRUPOCOMPROMISSOSUBGRUPO
           ,IDGRUPOCOMPROMISSOPAI
           ,IDGRUPOCOMPROMISSO)
     VALUES
           (@IDGRUPOCOMPROMISSOSUBGRUPO
           ,@IDGRUPOCOMPROMISSOPAI
           ,@IDGRUPOCOMPROMISSO)