SELECT GP.IDGRUPOPRODUTO
      ,GP.CODGRUPOPRODUTO
      ,GP.DESGRUPOPRODUTO
FROM INFM_GRUPOPRODUTO AS GP
WHERE IDEMPRESA = @IDEMPRESA AND NOT EXISTS (SELECT IDGRUPOPRODUTO 
										     FROM INFM_GRUPOPRODUTOSUBGRUPO
										     WHERE IDGRUPOPRODUTO = GP.IDGRUPOPRODUTO)