SELECT GC.IDGRUPOCOMPROMISSO
      ,GC.CODGRUPOCOMPROMISSO
      ,GC.DESGRUPOCOMPROMISSO
FROM INFM_GRUPOCOMPROMISSO GC
WHERE GC.IDEMPRESA = @IDEMPRESA AND NOT EXISTS (SELECT IDGRUPOCOMPROMISSO 
										     FROM INFM_GRUPOCOMPROMISSOSUBGRUPO
										     WHERE IDGRUPOCOMPROMISSO = GC.IDGRUPOCOMPROMISSO)