SELECT GP.IDGRUPOPERMISSAO
      ,GP.DESGRUPO
	  ,P.IDPERMISSAO
	  ,P.CODPERMISSAO
	  ,P.DESPERMISSAO
	  ,P.BOLOBRIGATORIA
	  ,A.IDACAO
      ,A.CODACAO
      ,A.DESACAO
FROM INFM_GRUPOPERMISSAO AS GP
INNER JOIN INFM_GRUPOPERMISSAOACAO AS GPA ON GPA.IDGRUPOPERMISSAO = GP.IDGRUPOPERMISSAO
INNER JOIN INFM_PERMISSAO AS P ON P.IDPERMISSAO = GPA.IDPERMISSAO
INNER JOIN INFM_ACAO AS A ON A.IDACAO = GPA.IDACAO
WHERE GP.IDGRUPOPERMISSAO = @IDGRUPOPERMISSAO
