INSERT INTO INFM_GRUPOCOMPROMISSO
           (IDGRUPOCOMPROMISSO
           ,DESGRUPOCOMPROMISSO
           ,IDEMPRESA)
     VALUES
           (@IDGRUPOCOMPROMISSO
           ,@DESGRUPOCOMPROMISSO
           ,@IDEMPRESA)


