INSERT INTO INFM_GRUPOPRODUTOSUBGRUPO
           (IDGRUPOPRODUTOSUBGRUPO
           ,IDGRUPOPRODUTOPAI
           ,IDGRUPOPRODUTO)
     VALUES
           (@IDGRUPOPRODUTOSUBGRUPO
           ,@IDGRUPOPRODUTOPAI
           ,@IDGRUPOPRODUTO)