SELECT GC.IDGRUPOCOMPROMISSO,
       GCS.IDGRUPOCOMPROMISSO AS IDGRUPOCOMPROMISSOFILHO,
	   GC.CODGRUPOCOMPROMISSO,
	   GC.DESGRUPOCOMPROMISSO
FROM INFM_GRUPOCOMPROMISSO AS GC
LEFT JOIN INFM_GRUPOCOMPROMISSOSUBGRUPO AS GCS ON GCS.IDGRUPOCOMPROMISSOPAI = GC.IDGRUPOCOMPROMISSO
WHERE GC.IDGRUPOCOMPROMISSO = @IDGRUPOCOMPROMISSO