INSERT INTO INFM_GRUPOPERMISSAOACAO
           (IDGRUPOPERMISSAOACAO
           ,IDPERMISSAO
           ,IDACAO
           ,IDGRUPOPERMISSAO)
     VALUES
           (@IDGRUPOPERMISSAOACAO
           ,@IDPERMISSAO
           ,@IDACAO
           ,@IDGRUPOPERMISSAO)