SELECT GP.IDGRUPOPRODUTO,
       GPP.IDGRUPOPRODUTO AS IDGRUPOPRODUTOFILHO,
	   GP.CODGRUPOPRODUTO,
	   GP.DESGRUPOPRODUTO
FROM INFM_GRUPOPRODUTO AS GP
LEFT JOIN INFM_GRUPOPRODUTOSUBGRUPO AS GPP ON GPP.IDGRUPOPRODUTOPAI = GP.IDGRUPOPRODUTO
WHERE GP.IDGRUPOPRODUTO = @IDGRUPOPRODUTO
