INSERT INTO INFM_RESPOSTAPERGUNTA
           (IDRESPOSTAPERGUNTA
           ,IDPERGUNTA
           ,IDPESSOACRM
           ,DESVALOR)
     VALUES
           (@IDRESPOSTAPERGUNTA
           ,@IDPERGUNTA
           ,@IDPESSOACRM
           ,@DESVALOR)