SELECT P.IDPERGUNTA
      ,P.DESPERGUNTA
      ,P.BOLOBRIGATORIA
      ,P.CODTIPOCOMPONENTE
      ,P.BOLNUMERICO
      ,RP.DESVALOR
FROM INFM_PERGUNTAS AS P
INNER JOIN INFM_RESPOSTAPERGUNTA AS RP ON RP.IDPERGUNTA = P.IDPERGUNTA
WHERE RP.IDPESSOACRM = @IDPESSOACRM