INSERT INTO INFM_PERGUNTAOPCAO
           (IDPERGUNTAOPCAO
           ,IDPERGUNTA
           ,DESPERGUNTAOPCAO)
     VALUES
           (@IDPERGUNTAOPCAO
           ,@IDPERGUNTA
           ,@DESPERGUNTAOPCAO)