INSERT INTO INFM_USUPERMISSAOACAO
           (IDUSUPERMISSAOACAO
           ,IDPERMISSAO
           ,IDACAO
           ,IDPESSOA
           ,IDGRUPOPERMISSAO)
     VALUES
           (@IDUSUPERMISSAOACAO
           ,@IDPERMISSAO
           ,@IDACAO
           ,@IDPESSOA
           ,@IDGRUPOPERMISSAO)