SELECT DISTINCT P.IDPERMISSAO,
				P.CODPERMISSAO,
				P.DESPERMISSAO,
				UPA.IDGRUPOPERMISSAO,
				A.IDACAO,
				A.CODACAO,
				A.DESACAO
FROM INFM_USUPERMISSAOACAO AS UPA
INNER JOIN INFM_PERMISSAO AS P ON P.IDPERMISSAO = UPA.IDPERMISSAO
INNER JOIN INFM_ACAO AS A ON A.IDACAO = UPA.IDACAO
WHERE UPA.IDPESSOA = @IDPESSOA
ORDER BY P.IDPERMISSAO