SELECT P.IDPERMISSAO
      ,P.CODPERMISSAO
      ,P.DESPERMISSAO
      ,P.BOLOBRIGATORIA
      ,A.IDACAO
      ,A.CODACAO
      ,A.DESACAO
FROM INFM_PERMISSAO AS P
INNER JOIN INFM_PERMISSAOACAO AS PA ON PA.IDPERMISSAO = P.IDPERMISSAO
INNER JOIN INFM_ACAO AS A ON A.IDACAO = PA.IDACAO
 