SELECT P.IDPESSOA
      ,P.CODPESSOA
      ,P.DESNOME
      ,P.DESCPF
      ,P.DESCNPJ
      ,P.CODLOGIN
	  ,P.BOLFUNICIONARIOATIVO
	  ,P.BOLFORNECEDORATIVO
	  ,TP.CODTIPOPESSOA
	  ,TP.IDTIPOPESSOA
	  ,TP.DESTIPOPESSOA
	  ,SP.CODSITUACAO
	  ,SP.DESSITUACAO
	  ,TE.IDTIPOEMPREGADO
	  ,TE.DESTIPOEMPREGADO	  
FROM INFM_PESSOA P
INNER JOIN INFM_TIPOPESSOA_PESSOA TPP ON TPP.IDPESSOA = P.IDPESSOA
INNER JOIN INFM_TIPOPESSOA TP ON TP.IDTIPOPESSOA = TPP.IDTIPOPESSOA
INNER JOIN INFM_EMPRESA E ON E.IDEMPRESA = P.IDEMPRESA
LEFT JOIN INFM_SITUACAO_PESSOA SP ON SP.IDSITUACAOPESSOA = P.IDSITUACAOPESSOA
LEFT JOIN INFM_TIPOEMPREGADO TE ON TE.IDTIPOEMPREGADO = P.IDTIPOEMPREGADO
LEFT JOIN INFM_FILIALPESSOA FP ON FP.IDPESSOA = P.IDPESSOA
LEFT JOIN INFM_FILIAL F ON F.IDFILIAL = FP.IDFILIAL
WHERE TP.CODTIPOPESSOA = @CODTIPOPESSOA AND E.IDEMPRESA = @IDEMPRESA
{0}