INSERT INTO INFM_UNIDADEMEDPRODUTO
           (IDUNIDADEMEDPRODUTO
           ,IDUNIDADEMEDIDA
           ,IDPRODUTOSERVICO)
     VALUES
           (@IDUNIDADEMEDPRODUTO
           ,@IDUNIDADEMEDIDA
           ,@IDPRODUTOSERVICO)