SELECT IDPRODUTOFILIAL
      ,IDPRODUTOCOMISSAO
	  ,IDUNIDADEMEDIDAESTOQUE
	  ,IDUNIDADEMEDIDAVENDA
      ,DESPRATELEIRA
      ,NUMESTOQUEMINIMO
      ,NUMMINIMOVENDA
      ,NUMIPIPER
      ,NUMEMBALAGEMPER
      ,NUMFRETEPER
      ,NUMOUTDESPPER
FROM INFM_PRODUTOFILIAL
WHERE IDPRODUTOFILIAL = @IDPRODUTOFILIAL
