UPDATE INFM_PRODUTOCOMISSAO
   SET DESPRODUTOCOMISSAO = @DESPRODUTOCOMISSAO
      ,NUMCOMISSAOPER = @NUMCOMISSAOPER
      ,NUMCOMISSAOVALOR = @NUMCOMISSAOVALOR
	  ,BOLHABILITADA = @BOLHABILITADA
 WHERE IDPRODUTOCOMISSAO = @IDPRODUTOCOMISSAO