UPDATE INFM_PRODUTOSERVICO
   SET IDTIPOPRODUTO = @IDTIPOPRODUTO
      ,IDGRUPOPRODUTO = @IDGRUPOPRODUTO
      ,IDCOR = @IDCOR
      ,IDPRODUTODERIVACAO = @IDPRODUTODERIVACAO
      ,IDPRODCATEGORIA = @IDPRODCATEGORIA
      ,IDPRODUTOMARCA = @IDPRODUTOMARCA
      ,DESPRODUTO = @DESPRODUTO
      ,OBSPRODUTO = @OBSPRODUTO
      ,NUMPESOPRODUTO = @NUMPESOPRODUTO
	  ,IDPRODUTONCM = @IDPRODUTONCM
	  ,IDPRODUTOCST = @IDPRODUTOCST
	  ,IDPRODUTOCFOP = @IDPRODUTOCFOP
	  ,BOLVENDAAGRANEL  = @BOLVENDAAGRANEL   
	  ,BOLINTERNO = @BOLINTERNO         
	  ,BOLACRESCIMO = @BOLACRESCIMO       
	  ,BOLVENDANUMEROSERIE = @BOLVENDANUMEROSERIE
      {0}
 WHERE IDPRODUTOSERVICO = @IDPRODUTOSERVICO