INSERT INTO INFM_PRODUTOCOMISSAO
           (IDPRODUTOCOMISSAO
           ,IDFILIAL
           ,DESPRODUTOCOMISSAO
           ,NUMCOMISSAOPER
           ,NUMCOMISSAOVALOR
           ,BOLHABILITADA)
     VALUES
           (@IDPRODUTOCOMISSAO
           ,@IDFILIAL
           ,@DESPRODUTOCOMISSAO
           ,@NUMCOMISSAOPER
           ,@NUMCOMISSAOVALOR
           ,@BOLHABILITADA)