UPDATE INFM_PRODUTOPROMOCAO
   SET DESPRODUTOPROMOCAO = @DESPRODUTOPROMOCAO
      ,NUMPROMOCAOPER = @NUMPROMOCAOPER
      ,NUMPROMOCAOVALOR = @NUMPROMOCAOVALOR
      ,BOLHABILITADA = @BOLHABILITADA
      ,DTHINICIO = @DTHINICIO
      ,DTHFIM = @DTHFIM
	  ,CODTIPOPROMOCAO = @CODTIPOPROMOCAO
	  ,IDEMPRESA = @IDEMPRESA
	  ,IDFILIAL = @IDFILIAL
	  ,BOL_POR_HORARIO = @BOL_POR_HORARIO
 WHERE IDPRODUTOPROMOCAO = @IDPRODUTOPROMOCAO