SELECT PM.IDPRODUTOPROMOCAO
      ,PM.CODPRODUTOPROMOCAO
      ,PM.DESPRODUTOPROMOCAO
      ,PM.NUMPROMOCAOPER
      ,PM.NUMPROMOCAOVALOR
      ,PM.BOLHABILITADA
      ,PM.DTHINICIO
      ,PM.DTHFIM
      ,SUM(DCP.NUMESTOQUE) AS NUMESTOQUE
FROM INFM_PRODUTOPROMOCAO AS PM
INNER JOIN INFM_PRODUTOPROMOCAOPRODF AS PPPDF ON PPPDF.IDPRODUTOPROMOCAO = PM.IDPRODUTOPROMOCAO
INNER JOIN INFM_PRODUTOFILIAL AS PF ON PF.IDPRODUTOFILIAL = PPPDF.IDPRODUTOFILIAL
INNER JOIN INFM_PRODUTOSERVICO AS PS ON PS.IDPRODUTOSERVICO = PF.IDPRODUTOSERVICO
LEFT JOIN INFM_DATOSCOMPRAPROD AS DCP ON DCP.IDPRODUTOFILIAL = PF.IDPRODUTOFILIAL
WHERE PF.IDFILIAL = @IDFILIAL {0}
GROUP BY PM.IDPRODUTOPROMOCAO,
         PM.CODPRODUTOPROMOCAO,
         PM.DESPRODUTOPROMOCAO,
		 PM.NUMPROMOCAOPER,
         PM.NUMPROMOCAOVALOR,
		 PM.BOLHABILITADA,
         PM.DTHINICIO,
		 PM.DTHFIM         
UNION
SELECT PM.IDPRODUTOPROMOCAO
      ,PM.CODPRODUTOPROMOCAO
      ,PM.DESPRODUTOPROMOCAO
      ,PM.NUMPROMOCAOPER
      ,PM.NUMPROMOCAOVALOR
      ,PM.BOLHABILITADA
      ,PM.DTHINICIO
      ,PM.DTHFIM
      ,SUM(DCP.NUMESTOQUE) AS NUMESTOQUE
FROM INFM_PRODUTOPROMOCAO AS PM
INNER JOIN INFM_PRODUTOPROMOCAOPRODF AS PPPDF ON PPPDF.IDPRODUTOPROMOCAO = PM.IDPRODUTOPROMOCAO
INNER JOIN INFM_PRODUTOSERVICO AS PS ON PS.IDPRODUTOSERVICO = PPPDF.IDPRODUTOSERVICO
INNER JOIN INFM_PRODUTOFILIAL AS PF ON PF.IDPRODUTOSERVICO = PS.IDPRODUTOSERVICO
LEFT JOIN INFM_DATOSCOMPRAPROD AS DCP ON DCP.IDPRODUTOFILIAL = PF.IDPRODUTOFILIAL
WHERE PS.IDEMPRESA = @IDEMPRESA {0}
GROUP BY PM.IDPRODUTOPROMOCAO,
         PM.CODPRODUTOPROMOCAO,
         PM.DESPRODUTOPROMOCAO,
		 PM.NUMPROMOCAOPER,
         PM.NUMPROMOCAOVALOR,
		 PM.BOLHABILITADA,
         PM.DTHINICIO,
		 PM.DTHFIM
UNION
SELECT PM.IDPRODUTOPROMOCAO
      ,PM.CODPRODUTOPROMOCAO
      ,PM.DESPRODUTOPROMOCAO
      ,PM.NUMPROMOCAOPER
      ,PM.NUMPROMOCAOVALOR
      ,PM.BOLHABILITADA
      ,PM.DTHINICIO
      ,PM.DTHFIM
      ,SUM(DCP.NUMESTOQUE) AS NUMESTOQUE
FROM INFM_PRODUTOPROMOCAO AS PM
INNER JOIN INFM_PRODUTOPROMOCAOPRODF AS PPPDF ON PPPDF.IDPRODUTOPROMOCAO = PM.IDPRODUTOPROMOCAO
INNER JOIN INFM_DATOSCOMPRAPROD AS DCP ON DCP.IDDATOSCOMPRAPROD = PPPDF.IDDATOSCOMPRAPROD
INNER JOIN INFM_PRODUTOFILIAL AS PF ON PF.IDPRODUTOFILIAL = DCP.IDPRODUTOFILIAL
INNER JOIN INFM_PRODUTOSERVICO AS PS ON PS.IDPRODUTOSERVICO = PF.IDPRODUTOSERVICO
WHERE PF.IDFILIAL = @IDFILIAL {0}
GROUP BY PM.IDPRODUTOPROMOCAO,
         PM.CODPRODUTOPROMOCAO,
         PM.DESPRODUTOPROMOCAO,
		 PM.NUMPROMOCAOPER,
         PM.NUMPROMOCAOVALOR,
		 PM.BOLHABILITADA,
         PM.DTHINICIO,
		 PM.DTHFIM