SELECT IDPRODUTOCOMISSAO
      ,IDFILIAL
      ,CODPRODUTOCOMISSAO
      ,DESPRODUTOCOMISSAO
      ,NUMCOMISSAOPER
      ,NUMCOMISSAOVALOR
      ,BOLHABILITADA
FROM INFM_PRODUTOCOMISSAO
WHERE IDFILIAL = @IDFILIAL