INSERT INTO INFM_OBSERVACAOPRODUTO
           (IDOBSERVACAOPRODUTO
           ,IDPRODUTOSERVICO
           ,IDOBSERVACAO)
     VALUES
           (@IDOBSERVACAOPRODUTO
           ,@IDPRODUTOSERVICO
           ,@IDOBSERVACAO)