SELECT PS.IDPRODUTOSERVICO
      ,PS.CODPRODUTO
      ,PS.DESPRODUTO
      ,PS.BOLVENDANUMEROSERIE
	  ,PS.BOLACRESCIMO
	  ,PS.BOLINTERNO
	  ,PS.BOLVENDAAGRANEL
	  ,CB.DESCODBARRAS
	  ,CB.IDCODIGOBARRASPRODSERV
	  {0}
FROM INFM_PRODUTOSERVICO AS PS
INNER JOIN INFM_TIPOPRODUTO AS TP ON TP.IDTIPOPRODUTO = PS.IDTIPOPRODUTO
LEFT JOIN INFM_CODIGOBARRASPRODSERV CB ON CB.IDPRODUTOSERVICO = PS.IDPRODUTOSERVICO
{1}
WHERE PS.IDEMPRESA = @IDEMPRESA