SELECT PS.CODPRODUTO
      ,PS.DESPRODUTO
      ,PS.DESCODBARRAS
      ,SUM(DCP.NUMESTOQUE) AS NUMESTOQUE
FROM INFM_PRODUTOPROMOCAO AS PM
INNER JOIN INFM_PRODUTOPROMOCAOPRODF AS PPPDF ON PPPDF.IDPRODUTOPROMOCAO = PM.IDPRODUTOPROMOCAO AND PPPDF.IDDATOSCOMPRAPROD IS NULL
INNER JOIN INFM_PRODUTOFILIAL AS PF ON PF.IDPRODUTOFILIAL = PPPDF.IDPRODUTOFILIAL
INNER JOIN INFM_PRODUTOSERVICO AS PS ON PS.IDPRODUTOSERVICO = PF.IDPRODUTOSERVICO
LEFT JOIN INFM_DATOSCOMPRAPROD AS DCP ON DCP.IDPRODUTOFILIAL = PF.IDPRODUTOFILIAL
WHERE PM.IDPRODUTOPROMOCAO = @IDPRODUTOPROMOCAO
GROUP BY PS.CODPRODUTO,
         PS.DESPRODUTO,
         PS.DESCODBARRAS       
UNION
SELECT PS.CODPRODUTO
      ,PS.DESPRODUTO
      ,PS.DESCODBARRAS
      ,SUM(DCP.NUMESTOQUE) AS NUMESTOQUE
FROM INFM_PRODUTOPROMOCAO AS PM
INNER JOIN INFM_PRODUTOPROMOCAOPRODF AS PPPDF ON PPPDF.IDPRODUTOPROMOCAO = PM.IDPRODUTOPROMOCAO  AND PPPDF.IDPRODUTOFILIAL IS NULL  AND PPPDF.IDDATOSCOMPRAPROD IS NULL
INNER JOIN INFM_PRODUTOSERVICO AS PS ON PS.IDPRODUTOSERVICO = PPPDF.IDPRODUTOSERVICO
INNER JOIN INFM_PRODUTOFILIAL AS PF ON PF.IDPRODUTOSERVICO = PS.IDPRODUTOSERVICO
LEFT JOIN INFM_DATOSCOMPRAPROD AS DCP ON DCP.IDPRODUTOFILIAL = PF.IDPRODUTOFILIAL
WHERE PM.IDPRODUTOPROMOCAO = @IDPRODUTOPROMOCAO
GROUP BY PS.CODPRODUTO,
         PS.DESPRODUTO,
         PS.DESCODBARRAS
UNION
SELECT PS.CODPRODUTO
      ,PS.DESPRODUTO
      ,PS.DESCODBARRAS
      ,SUM(DCP.NUMESTOQUE) AS NUMESTOQUE
FROM INFM_PRODUTOPROMOCAO AS PM
INNER JOIN INFM_PRODUTOPROMOCAOPRODF AS PPPDF ON PPPDF.IDPRODUTOPROMOCAO = PM.IDPRODUTOPROMOCAO
INNER JOIN INFM_DATOSCOMPRAPROD AS DCP ON DCP.IDDATOSCOMPRAPROD = PPPDF.IDDATOSCOMPRAPROD
INNER JOIN INFM_PRODUTOFILIAL AS PF ON PF.IDPRODUTOFILIAL = DCP.IDPRODUTOFILIAL
INNER JOIN INFM_PRODUTOSERVICO AS PS ON PS.IDPRODUTOSERVICO = PF.IDPRODUTOSERVICO
WHERE PM.IDPRODUTOPROMOCAO = @IDPRODUTOPROMOCAO
GROUP BY PS.CODPRODUTO,
         PS.DESPRODUTO,
         PS.DESCODBARRAS