SELECT PS.DESPRODUTO
      ,PS.IDPRODUTOSERVICO
	  ,PF.IDPRODUTOFILIAL
	  ,NULL AS IDDATOSCOMPRAPROD
      ,SUM(DCP.NUMESTOQUE) AS NUMESTOQUE
	  ,1 AS TIPO
FROM INFM_PRODUTOFILIAL AS PF
INNER JOIN INFM_PRODUTOSERVICO AS PS ON PS.IDPRODUTOSERVICO = PF.IDPRODUTOSERVICO
LEFT JOIN INFM_DATOSCOMPRAPROD AS DCP ON DCP.IDPRODUTOFILIAL = PF.IDPRODUTOFILIAL
LEFT JOIN INFM_COMPRA AS C ON C.IDCOMPRA = DCP.IDCOMPRA AND C.CODESTADO = 'CF'
WHERE PF.IDFILIAL = @IDFILIAL
GROUP BY PS.DESPRODUTO,
         PS.IDPRODUTOSERVICO,
		 PF.IDPRODUTOFILIAL        
UNION
SELECT PS.DESPRODUTO
      ,PS.IDPRODUTOSERVICO
	  ,NULL AS IDPRODUTOFILIAL
	  ,NULL AS IDDATOSCOMPRAPROD
      ,SUM(DCP.NUMESTOQUE) AS NUMESTOQUE
	  ,2 AS TIPO
FROM  INFM_PRODUTOSERVICO AS PS
INNER JOIN INFM_PRODUTOFILIAL AS PF ON PF.IDPRODUTOSERVICO = PS.IDPRODUTOSERVICO
LEFT JOIN INFM_DATOSCOMPRAPROD AS DCP ON DCP.IDPRODUTOFILIAL = PF.IDPRODUTOFILIAL
LEFT JOIN INFM_COMPRA AS C ON C.IDCOMPRA = DCP.IDCOMPRA AND C.CODESTADO = 'CF'
WHERE PS.IDEMPRESA = @IDEMPRESA
GROUP BY PS.DESPRODUTO,
         PS.IDPRODUTOSERVICO
UNION
SELECT PS.DESPRODUTO
      ,PS.IDPRODUTOSERVICO
	  ,PF.IDPRODUTOFILIAL
	  ,DCP.IDDATOSCOMPRAPROD
      ,SUM(DCP.NUMESTOQUE) AS NUMESTOQUE
	  ,3 AS TIPO
FROM INFM_DATOSCOMPRAPROD AS DCP
INNER JOIN INFM_PRODUTOFILIAL AS PF ON PF.IDPRODUTOFILIAL = DCP.IDPRODUTOFILIAL
INNER JOIN INFM_PRODUTOSERVICO AS PS ON PS.IDPRODUTOSERVICO = PF.IDPRODUTOSERVICO
LEFT JOIN INFM_COMPRA AS C ON C.IDCOMPRA = DCP.IDCOMPRA AND C.CODESTADO = 'CF'
WHERE PF.IDFILIAL = @IDFILIAL
GROUP BY PS.DESPRODUTO,
         PS.IDPRODUTOSERVICO,
		 PF.IDPRODUTOFILIAL,
		 DCP.IDDATOSCOMPRAPROD