INSERT INTO INFM_PRODUTODERIVACAO
           (IDPRODUTODERIVACAO
           ,DESPRODUTODERIVACAO
		   ,IDEMPRESA)
     VALUES
           (@IDPRODUTODERIVACAO
           ,@DESPRODUTODERIVACAO
		   ,@IDEMPRESA)