INSERT INTO INFM_PRODUTOPROMOCAOPRODF
           (IDPRODUTOPROMOCAOPRODF
           ,IDPRODUTOPROMOCAO
           ,IDPRODUTOFILIAL
           ,IDDATOSCOMPRAPROD
           ,IDPRODUTOSERVICO)
     VALUES
           (@IDPRODUTOPROMOCAOPRODF
           ,@IDPRODUTOPROMOCAO
           ,@IDPRODUTOFILIAL
           ,@IDDATOSCOMPRAPROD
           ,@IDPRODUTOSERVICO)