SELECT PP.IDPRODUTOPROMOCAO
      ,PP.CODPRODUTOPROMOCAO
      ,PP.DESPRODUTOPROMOCAO
      ,PP.NUMPROMOCAOPER
      ,PP.NUMPROMOCAOVALOR
      ,PP.BOLHABILITADA
	  ,PP.BOL_POR_HORARIO
      ,PP.DTHINICIO
      ,PP.DTHFIM
	  ,PP.CODTIPOPROMOCAO
	  ,PPPDF.IDPRODUTOFILIAL
      ,PPPDF.IDDATOSCOMPRAPROD
	  ,PPPDF.IDPRODUTOSERVICO
FROM INFM_PRODUTOPROMOCAO AS PP
INNER JOIN INFM_PRODUTOPROMOCAOPRODF AS PPPDF ON PPPDF.IDPRODUTOPROMOCAO = PP.IDPRODUTOPROMOCAO
WHERE PP.IDPRODUTOPROMOCAO = @IDPRODUTOPROMOCAO