INSERT INTO INFM_ACRESCIMOPRODUTO
           (IDACRESCIMOPRODUTO
           ,IDPRODUTOSERVICO
           ,IDACRESCIMO)
     VALUES
           (@IDACRESCIMOPRODUTO
           ,@IDPRODUTOSERVICO
           ,@IDACRESCIMO)