INSERT INTO INFM_CODIGOBARRASPRODSERV
           (IDCODIGOBARRASPRODSERV
           ,IDPRODUTOSERVICO
           ,IDEMPRESA
           ,DESCODBARRAS)
     VALUES
           (@IDCODIGOBARRASPRODSERV
           ,@IDPRODUTOSERVICO
           ,@IDEMPRESA
           ,@DESCODBARRAS)