INSERT INTO INFM_DIASEMANAPROMOCAO
           (IDDIASEMANAPROMOCAO
           ,IDPRODUTOPROMOCAO
           ,CODDIASEMANA)
     VALUES
           (@IDDIASEMANAPROMOCAO
           ,@IDPRODUTOPROMOCAO
           ,@CODDIASEMANA)