SELECT IDPRODUTOFILIAL
      ,IDPRODUTOCOMISSAO
	  ,IDUNIDADEMEDIDAESTOQUE
	  ,IDUNIDADEMEDIDAVENDA
      ,DESPRATELEIRA
      ,NUMESTOQUEMINIMO
      ,NUMMINIMOVENDA
      ,NUMIPIPER
      ,NUMEMBALAGEMPER
      ,NUMFRETEPER
      ,NUMOUTDESPPER
	  ,IDUMVALORVENDAVAREJO
	  ,IDUMVENDAATACADO
	  ,IDUMVALORVENATACADO
	  ,NUMVALORVENDAVAREJO
	  ,NUMVALORVENDAATACADO
	  ,NUMQUANTVENDAATACADO
	  ,NUMPERCENTDESCONTATAC
	  ,IDSETOREMPRESA
FROM INFM_PRODUTOFILIAL
WHERE IDFILIAL = @IDFILIAL AND IDPRODUTOSERVICO = @IDPRODUTOSERVICO
