UPDATE INFM_PROPOSTA
   SET IDCRM = @IDCRM
      ,DESPROPOSTA = @DESPROPOSTA
      ,NUMPROPOSTAVENDA = @NUMPROPOSTAVENDA
      ,NUMPROPOSTAMANUTENCAO = @NUMPROPOSTAMANUTENCAO
      ,NUMCONTRAPROPOSTAVENDA = @NUMCONTRAPROPOSTAVENDA
      ,NUMCONTRAPROPOSTAMANUT = @NUMCONTRAPROPOSTAMANUT
      ,DESOPNIAO = @DESOPNIAO
      ,DESDUVIDA = @DESDUVIDA
      ,BOLATENDENECESSIDADE = @BOLATENDENECESSIDADE
      ,DTINSTALACAO = @DTINSTALACAO
      ,BOLATIVA = @BOLATIVA
      ,IDPESSOA = @IDPESSOA
      ,IDPESSOACLIENTE = @IDPESSOACLIENTE
 WHERE IDPROPOSTA = @IDPROPOSTA