SELECT IDPROPOSTA
      ,IDCRM
      ,DESPROPOSTA
      ,NUMPROPOSTAVENDA
      ,NUMPROPOSTAMANUTENCAO
      ,NUMCONTRAPROPOSTAVENDA
      ,NUMCONTRAPROPOSTAMANUT
      ,DESOPNIAO
      ,DESDUVIDA
      ,BOLATENDENECESSIDADE
      ,DTINSTALACAO
      ,BOLATIVA
      ,CODPROPOSTA
	  ,IDPESSOA
	  ,IDPESSOACLIENTE
  FROM INFM_PROPOSTA
  WHERE IDEMPRESA = @IDEMPRESA