SELECT IDPROPOSTA
      ,IDCRM
      ,IDEMPRESA
      ,DESPROPOSTA
      ,NUMPROPOSTAVENDA
      ,NUMPROPOSTAMANUTENCAO
      ,NUMCONTRAPROPOSTAVENDA
      ,NUMCONTRAPROPOSTAMANUT
      ,DESOPNIAO
      ,DESDUVIDA
      ,BOLATENDENECESSIDADE
      ,DTINSTALACAO
      ,BOLATIVA
      ,CODPROPOSTA
      ,IDPESSOA
      ,IDPESSOACLIENTE
FROM INFM_PROPOSTA
WHERE IDPROPOSTA = @IDPROPOSTA
