INSERT INTO INFM_PUBLICIDADE
           (IDPUBLICIDADE
           ,DESPUBLICIDADE
           ,CODPUBLICIDADE)
     VALUES
           (@IDPUBLICIDADE
           ,@DESPUBLICIDADE
           ,(SELECT MAX(CODPUBLICIDADE) + 1 FROM INFM_PUBLICIDADE))