INSERT INTO INFM_SEGMENTOCOMERCIAL
           (IDSEGMENTOCOMERCIAL
           ,DESSEGMENTOCOMERCIAL
           ,IDEMPRESA)
     VALUES
           (@IDSEGMENTOCOMERCIAL
           ,@DESSEGMENTOCOMERCIAL
           ,@IDEMPRESA)