UPDATE INFM_UNIDADEMEDIDA
   SET IDUNIDADEMEDIDAPAI = @IDUNIDADEMEDIDAPAI
      ,CODUNIDADEMEDIDA = @CODUNIDADEMEDIDA
      ,NUMUNIDADEPAI = @NUMUNIDADEPAI
      ,DESUNIDADEMEDIDA = @DESUNIDADEMEDIDA
 WHERE IDUNIDADEMEDIDA = @IDUNIDADEMEDIDA