SELECT 1
FROM INFM_UNIDADEMEDIDA
WHERE IDUNIDADEMEDIDAPAI = @IDUNIDADEMEDIDA
UNION
SELECT 1
FROM INFM_PRODUTOSERVICO
WHERE IDUNIDADEMEDIDA = @IDUNIDADEMEDIDA
UNION
SELECT 1
FROM INFM_DATOSCOMPRAPROD
WHERE IDUNIDADEMEDIDA = @IDUNIDADEMEDIDA
UNION
SELECT 1
FROM INFM_PRODUTOFILIAL
WHERE IDUNIDADEMEDIDA = @IDUNIDADEMEDIDA