SELECT UM.IDUNIDADEMEDIDA,
       UM.IDUNIDADEMEDIDAPAI,
       UM.CODUNIDADEMEDIDA,
	   UM.NUMUNIDADEPAI,
       UM.DESUNIDADEMEDIDA
FROM INFM_UNIDADEMEDPRODUTO AS UP
INNER JOIN INFM_UNIDADEMEDIDA AS UM ON UM.IDUNIDADEMEDIDA = UP.IDUNIDADEMEDIDA
WHERE UP.IDPRODUTOSERVICO = @IDPRODUTOSERVICO