INSERT INTO INFM_UNIDADEMEDIDA
           (IDUNIDADEMEDIDA
           ,IDUNIDADEMEDIDAPAI
           ,CODUNIDADEMEDIDA
           ,NUMUNIDADEPAI
           ,DESUNIDADEMEDIDA
		   ,IDEMPRESA)
     VALUES
           (@IDUNIDADEMEDIDA
           ,@IDUNIDADEMEDIDAPAI
           ,@CODUNIDADEMEDIDA
           ,@NUMUNIDADEPAI
           ,@DESUNIDADEMEDIDA
		   ,@IDEMPRESA)