SELECT P.IDPESSOA, 
	   P.CODPESSOA, 
	   P.DESNOME, 
	   P.CODLOGIN,
	   P.BOLALTERARSENHA,
	   P.BOLCONSULTOR,
	   TE.BOLSUPERVISOR,
	   TE.BOLRESPFINANCEIRO,
	   TE.BOLENTREGADOR,
	   TE.BOLGERENTE
FROM INFM_PESSOA AS P
INNER JOIN INFM_TIPOPESSOA_PESSOA TPP ON TPP.IDPESSOA = P.IDPESSOA
INNER JOIN INFM_TIPOPESSOA AS TP ON TP.IDTIPOPESSOA = TPP.IDTIPOPESSOA AND TP.CODTIPOPESSOA = 1
LEFT JOIN INFM_TIPOEMPREGADO AS TE ON TE.IDTIPOEMPREGADO = P.IDTIPOEMPREGADO
WHERE P.CODLOGIN = @CODLOGIN AND P.DESSENHA = @DESSENHA
