QUERYVALIDACAO select 1 FROM INFM_TIPOPESSOA WHERE CODTIPOPESSOA = 1
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_TIPOPESSOA
           (IDTIPOPESSOA
           ,DESTIPOPESSOA
           ,CODTIPOPESSOA)
     VALUES
           (1
           ,'Funcionario'
           ,1)