QUERYVALIDACAO select 1 FROM INFM_PESSOA WHERE CODLOGIN = 'administrador'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_PESSOA
           (IDENDERECO
           ,IDPESSOA
           ,IDSITUACAOPESSOA
           ,IDPESSOARESPONSAVEL
           ,IDSEGMENTOCOMERCIAL
           ,IDENDERECOEMPRESA
           ,DESNOME
           ,DESNOMEFANTASIA
           ,DESRG
           ,DTHNASCIMENTO
           ,DESCPF
           ,DESCNPJ
           ,DTHCADASTRO
           ,DESINSCRICAOESTADUAL
           ,DESTELEFONEFIXO
           ,DESTELEFONEFAX
           ,DESTELEFONECELULAR
           ,DESHABILITACAO
           ,NUMCOMISSAO
           ,NUMSALARIO
           ,DTHADMISSAO
           ,DESCONTATO
           ,OBSPESSOA
           ,NUMLIMITE
           ,DESEMAIL
           ,DESNOMEPAI
           ,DESNOMEMAE
           ,DESEMPRESA
           ,DESFONEEMPRESA
           ,DESCARGO
           ,OBSREFPESSOAL
           ,DTHALMOCOINICIO
           ,DTHALMOCOFIM
           ,CODLOGIN
           ,DESSENHA
           ,CODTABMERCADORIA
           ,BOLALTERARSENHA
	   ,BOLFUNICIONARIOATIVO
	   ,BOLFORNECEDORATIVO
	   ,NUMENDERECO
	   ,DESCOMPLEMENTOENDER
	   ,DESPONTOREFERENCIA
	   ,CODTABELAMERCADORIA
	   ,NUMENDERECOEMP
	   ,DESCOMPLEMENTOENDEREMP
	   ,DESPONTOREFERENCIAEMP)
     VALUES
           (NULL
           ,'1'
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,'Administrador'
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,'administrador'
           ,'1'
           ,NULL
           ,1
	   ,1
           ,0
	   ,NULL
	   ,NULL
	   ,NULL
	   ,NULL
	   ,NULL
	   ,NULL
	   ,NULL)