QUERYVALIDACAO select 1 FROM INFM_TIPOPESSOA_PESSOA WHERE IDTIPOPESSOA = '1' AND IDPESSOA = '1'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_TIPOPESSOA_PESSOA
           (IDTIPOPESSOAPESSOA
           ,IDTIPOPESSOA
           ,IDPESSOA)
     VALUES
           ('1'
           ,'1'
           ,'1')