QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'PR'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('15',
             'PR',
             'PARANA')