QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'PA'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('17',
             'PA',
             'PARÁ')