SELECT IDLICENCA
      ,CODLICENCA
      ,SESSOESINFINITAS
      ,NUMQUANTIDADESESSOES
      ,NUMVALIDADE
      ,VALIDADEINFINITA
      ,CHAVEATIVA
	  ,NUMQUANTIDADEACESSOS
	  ,DATAATIVACAO
FROM INFMA_LICENCA
WHERE IDLICENCA = @IDLICENCA