INSERT INTO INFMA_LICENCA
           (IDLICENCA
           ,CODLICENCA
           ,SESSOESINFINITAS
           ,NUMQUANTIDADESESSOES
           ,NUMVALIDADE
           ,VALIDADEINFINITA
           ,CHAVEATIVA
		   ,NUMQUANTIDADEACESSOS)
     VALUES
           (@IDLICENCA
           ,@CODLICENCA
           ,@SESSOESINFINITAS
           ,@NUMQUANTIDADESESSOES
           ,@NUMVALIDADE
           ,@VALIDADEINFINITA
           ,@CHAVEATIVA
		   ,@NUMQUANTIDADEACESSOS)