//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_PARCELAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_PARCELAMENTO()
        {
            this.INFM_TRANSACOES = new HashSet<INFM_TRANSACOES>();
        }
    
        public string IDPARCELAMENTO { get; set; }
        public string IDDOCUMENTO { get; set; }
        public System.DateTime DTHVENCATUAL { get; set; }
        public System.DateTime DTHVENCORIGINAL { get; set; }
        public decimal NUMVALORORIGINAL { get; set; }
        public int NUMPARCELA { get; set; }
    
        public virtual INFM_DOCUMENTO INFM_DOCUMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_TRANSACOES> INFM_TRANSACOES { get; set; }
    }
}
