//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_PESSOACRM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_PESSOACRM()
        {
            this.INFM_PESSOACRMPESSOA = new HashSet<INFM_PESSOACRMPESSOA>();
            this.INFM_RESPOSTAPERGUNTA = new HashSet<INFM_RESPOSTAPERGUNTA>();
        }
    
        public string IDPESSOACRM { get; set; }
        public string IDCRM { get; set; }
        public System.DateTime DTHPROXAGENDAMENTO { get; set; }
        public Nullable<System.DateTime> DTHPROXAGENDAMENTOFIN { get; set; }
        public string IDGRUPOCOMPROMISSO { get; set; }
        public string DESAGENDAMENTO { get; set; }
        public Nullable<bool> BOLCONCLUIDO { get; set; }
    
        public virtual INFM_CRM INFM_CRM { get; set; }
        public virtual INFM_GRUPOCOMPROMISSO INFM_GRUPOCOMPROMISSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PESSOACRMPESSOA> INFM_PESSOACRMPESSOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_RESPOSTAPERGUNTA> INFM_RESPOSTAPERGUNTA { get; set; }
    }
}
