//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_SEGMENTOCOMERCIAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_SEGMENTOCOMERCIAL()
        {
            this.INFM_PESSOA = new HashSet<INFM_PESSOA>();
        }
    
        public string IDSEGMENTOCOMERCIAL { get; set; }
        public int CODSEGMENTOCOMERCIAL { get; set; }
        public string DESSEGMENTOCOMERCIAL { get; set; }
        public string IDEMPRESA { get; set; }
    
        public virtual INFM_EMPRESA INFM_EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PESSOA> INFM_PESSOA { get; set; }
    }
}
