//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_GRUPOCOMPROMISSO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_GRUPOCOMPROMISSO()
        {
            this.INFM_GRUPOCOMPROMISSOSUBGRUPO = new HashSet<INFM_GRUPOCOMPROMISSOSUBGRUPO>();
            this.INFM_GRUPOCOMPROMISSOSUBGRUPO1 = new HashSet<INFM_GRUPOCOMPROMISSOSUBGRUPO>();
            this.INFM_GRUPOCOMPROMISSOSUBGRUPO2 = new HashSet<INFM_GRUPOCOMPROMISSOSUBGRUPO>();
            this.INFM_PERGUNTAS = new HashSet<INFM_PERGUNTAS>();
            this.INFM_PESSOACRM = new HashSet<INFM_PESSOACRM>();
        }
    
        public string IDGRUPOCOMPROMISSO { get; set; }
        public int CODGRUPOCOMPROMISSO { get; set; }
        public string DESGRUPOCOMPROMISSO { get; set; }
        public string IDEMPRESA { get; set; }
    
        public virtual INFM_EMPRESA INFM_EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_GRUPOCOMPROMISSOSUBGRUPO> INFM_GRUPOCOMPROMISSOSUBGRUPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_GRUPOCOMPROMISSOSUBGRUPO> INFM_GRUPOCOMPROMISSOSUBGRUPO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_GRUPOCOMPROMISSOSUBGRUPO> INFM_GRUPOCOMPROMISSOSUBGRUPO2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PERGUNTAS> INFM_PERGUNTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PESSOACRM> INFM_PESSOACRM { get; set; }
    }
}
