//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_TIPOCRMCONFIG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_TIPOCRMCONFIG()
        {
            this.INFM_TIPOCRMCONFIGPESSOA = new HashSet<INFM_TIPOCRMCONFIGPESSOA>();
        }
    
        public string IDTIPOCRMCONFIG { get; set; }
        public string IDTIPOCRM { get; set; }
        public string IDTIPOEMPREGADO { get; set; }
        public bool BOLEMPREGADOATUAL { get; set; }
        public Nullable<int> NELQUANTDIASDATA { get; set; }
        public int NELQUANTFUNCIONARIOS { get; set; }
        public int NELNIVEL { get; set; }
        public string DESNIVELCONFIG { get; set; }
    
        public virtual INFM_TIPOCRM INFM_TIPOCRM { get; set; }
        public virtual INFM_TIPOEMPREGADO INFM_TIPOEMPREGADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_TIPOCRMCONFIGPESSOA> INFM_TIPOCRMCONFIGPESSOA { get; set; }
    }
}
