//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_CODIGOBARRASPESSOA
    {
        public string IDCODIGOBARRASPESSOA { get; set; }
        public string IDPESSOA { get; set; }
        public string DESCODIGOBARRASPESSOA { get; set; }
        public bool BOLATIVO { get; set; }
        public System.DateTime DTHCODIGO { get; set; }
        public Nullable<decimal> NUMVALOR { get; set; }
    
        public virtual INFM_PESSOA INFM_PESSOA { get; set; }
    }
}
