//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_STATUSCRMAGRUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_STATUSCRMAGRUP()
        {
            this.INFM_STATUS_CRM = new HashSet<INFM_STATUS_CRM>();
            this.INFM_TIPOCRM = new HashSet<INFM_TIPOCRM>();
        }
    
        public string IDSTATUSCRMAGRUP { get; set; }
        public string IDEMPRESA { get; set; }
        public string DESSTATUSCRMAGRUP { get; set; }
    
        public virtual INFM_EMPRESA INFM_EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_STATUS_CRM> INFM_STATUS_CRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_TIPOCRM> INFM_TIPOCRM { get; set; }
    }
}
