//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_CIDADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_CIDADE()
        {
            this.INFM_BAIRRO = new HashSet<INFM_BAIRRO>();
        }
    
        public string IDCIDADE { get; set; }
        public string IDESTADO { get; set; }
        public string DESCIDADE { get; set; }
        public int CODCIDADE { get; set; }
        public string CODDDD { get; set; }
        public string CODIBGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_BAIRRO> INFM_BAIRRO { get; set; }
        public virtual INFM_ESTADO INFM_ESTADO { get; set; }
    }
}
