//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_PRODUTOVALORDINAMICO
    {
        public string IDPRODUTOVALORDINAMICO { get; set; }
        public string IDPRODUTOFILIAL { get; set; }
        public string DESHORAINICIO { get; set; }
        public string DESHORAFIM { get; set; }
        public bool BOLHORARIO { get; set; }
        public string CODDIA { get; set; }
        public Nullable<decimal> NUMVALORDESCONTO { get; set; }
        public Nullable<decimal> NUMPERCENTDESCONTO { get; set; }
    
        public virtual INFM_PRODUTOFILIAL INFM_PRODUTOFILIAL { get; set; }
        public virtual INFM_PRODUTOFILIAL INFM_PRODUTOFILIAL1 { get; set; }
    }
}
