//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_LOGERROR
    {
        public string IDLOGERROR { get; set; }
        public string DESERROR { get; set; }
        public string DESPESSOA { get; set; }
        public System.DateTime DTHERROR { get; set; }
    }
}
