//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_ITEMVENDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_ITEMVENDA()
        {
            this.INFM_ITEMVENDAACRESCIMO = new HashSet<INFM_ITEMVENDAACRESCIMO>();
            this.INFM_ITEMVENDA_NUMSERIE = new HashSet<INFM_ITEMVENDA_NUMSERIE>();
            this.INFM_ITEMVENDAOBSERVACAO = new HashSet<INFM_ITEMVENDAOBSERVACAO>();
        }
    
        public string IDITEMVENDA { get; set; }
        public string IDVENDA { get; set; }
        public string IDPESSOAVENDA { get; set; }
        public string IDPRODUTOSERVICO { get; set; }
        public bool BOLCANCELADO { get; set; }
        public decimal NUMVALORITEM { get; set; }
        public Nullable<decimal> NUMVALORDESCONTO { get; set; }
        public decimal NUMVALORTOTAL { get; set; }
        public Nullable<decimal> NUMQUANTIDADE { get; set; }
        public Nullable<decimal> NUMVALORACRESCIMO { get; set; }
        public Nullable<int> NUMSEQUENCIA { get; set; }
        public string CODESTADO { get; set; }
        public string IDPESSOACANCELAMENTO { get; set; }
        public string IDPAGAMENTO { get; set; }
        public Nullable<bool> BOLCONCLUIDO { get; set; }
    
        public virtual INFM_PRODUTOSERVICO INFM_PRODUTOSERVICO { get; set; }
        public virtual INFM_PESSOA INFM_PESSOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_ITEMVENDAACRESCIMO> INFM_ITEMVENDAACRESCIMO { get; set; }
        public virtual INFM_PAGAMENTO INFM_PAGAMENTO { get; set; }
        public virtual INFM_PESSOA INFM_PESSOA1 { get; set; }
        public virtual INFM_VENDA INFM_VENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_ITEMVENDA_NUMSERIE> INFM_ITEMVENDA_NUMSERIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_ITEMVENDAOBSERVACAO> INFM_ITEMVENDAOBSERVACAO { get; set; }
    }
}
