//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_GRUPOCOMPROMISSOSUBGRUPO
    {
        public string IDGRUPOCOMPROMISSOSUBGRUPO { get; set; }
        public string IDGRUPOCOMPROMISSOPAI { get; set; }
        public string IDGRUPOCOMPROMISSO { get; set; }
    
        public virtual INFM_GRUPOCOMPROMISSO INFM_GRUPOCOMPROMISSO { get; set; }
        public virtual INFM_GRUPOCOMPROMISSO INFM_GRUPOCOMPROMISSO1 { get; set; }
        public virtual INFM_GRUPOCOMPROMISSO INFM_GRUPOCOMPROMISSO2 { get; set; }
    }
}
