//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_EMPRESA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_EMPRESA()
        {
            this.INFM_ADMINISTRADORA = new HashSet<INFM_ADMINISTRADORA>();
            this.INFM_CAIXA = new HashSet<INFM_CAIXA>();
            this.INFM_CAIXA1 = new HashSet<INFM_CAIXA>();
            this.INFM_CODIGOBARRASPRODSERV = new HashSet<INFM_CODIGOBARRASPRODSERV>();
            this.INFM_COMPRA = new HashSet<INFM_COMPRA>();
            this.INFM_COR = new HashSet<INFM_COR>();
            this.INFM_CRM = new HashSet<INFM_CRM>();
            this.INFM_GRUPOPERMISSAO = new HashSet<INFM_GRUPOPERMISSAO>();
            this.INFM_GRUPOPRODUTO = new HashSet<INFM_GRUPOPRODUTO>();
            this.INFM_PRODUTOMARCA = new HashSet<INFM_PRODUTOMARCA>();
            this.INFM_PRODCATEGORIA = new HashSet<INFM_PRODCATEGORIA>();
            this.INFM_PRODUTODERIVACAO = new HashSet<INFM_PRODUTODERIVACAO>();
            this.INFM_PRODUTOSERVICO = new HashSet<INFM_PRODUTOSERVICO>();
            this.INFM_FILIAL = new HashSet<INFM_FILIAL>();
            this.INFM_FORMAPAGAMENTO = new HashSet<INFM_FORMAPAGAMENTO>();
            this.INFM_GRUPOCOMPROMISSO = new HashSet<INFM_GRUPOCOMPROMISSO>();
            this.INFM_INTEGRACAOAPI = new HashSet<INFM_INTEGRACAOAPI>();
            this.INFM_OBSERVACAO = new HashSet<INFM_OBSERVACAO>();
            this.INFM_PARAMETROVALOR = new HashSet<INFM_PARAMETROVALOR>();
            this.INFM_PESSOA1 = new HashSet<INFM_PESSOA>();
            this.INFM_PRODUTOPROMOCAO = new HashSet<INFM_PRODUTOPROMOCAO>();
            this.INFM_PRODUTONCM = new HashSet<INFM_PRODUTONCM>();
            this.INFM_PROPOSTA = new HashSet<INFM_PROPOSTA>();
            this.INFM_PRODUTONUMEROSERIE = new HashSet<INFM_PRODUTONUMEROSERIE>();
            this.INFM_SEGMENTOCOMERCIAL = new HashSet<INFM_SEGMENTOCOMERCIAL>();
            this.INFM_SETOREMPRESA = new HashSet<INFM_SETOREMPRESA>();
            this.INFM_STATUS_CRM = new HashSet<INFM_STATUS_CRM>();
            this.INFM_STATUSCRMAGRUP = new HashSet<INFM_STATUSCRMAGRUP>();
            this.INFM_TIPOCRM = new HashSet<INFM_TIPOCRM>();
            this.INFM_TIPOEMPREGADO = new HashSet<INFM_TIPOEMPREGADO>();
            this.INFM_UNIDADEMEDIDA = new HashSet<INFM_UNIDADEMEDIDA>();
            this.INFM_VENDA = new HashSet<INFM_VENDA>();
            this.INFM_PRODUTOCST = new HashSet<INFM_PRODUTOCST>();
            this.INFM_PRODUTOCFOP = new HashSet<INFM_PRODUTOCFOP>();
            this.INFM_PROCESSO = new HashSet<INFM_PROCESSO>();
        }
    
        public string IDEMPRESA { get; set; }
        public int CODEMPRESA { get; set; }
        public string DESEMPRESA { get; set; }
        public string DESCNPJ { get; set; }
        public string DESINSCRICAOESTADUAL { get; set; }
        public string CODACESSO { get; set; }
        public string CODLICENCA { get; set; }
        public Nullable<int> NUMQUANTIDADESESSOES { get; set; }
        public Nullable<int> NUMQUANTIDADEACESSADA { get; set; }
        public Nullable<int> NUMQUANTIDADEACESSO { get; set; }
        public Nullable<bool> SESSOSILIMITADAS { get; set; }
        public Nullable<bool> VALIDADEILIMITADA { get; set; }
        public Nullable<bool> BOLEMPRESAMESTE { get; set; }
        public string IDLICENCA { get; set; }
        public string IDPUBLICIDADE { get; set; }
        public string DESAMIGO { get; set; }
        public string IDPESSOA { get; set; }
        public string DESEMAIL { get; set; }
        public string DESSENHA { get; set; }
        public string DESSMTP { get; set; }
        public Nullable<bool> BOLSSL { get; set; }
        public Nullable<int> CODPORTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_ADMINISTRADORA> INFM_ADMINISTRADORA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_CAIXA> INFM_CAIXA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_CAIXA> INFM_CAIXA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_CODIGOBARRASPRODSERV> INFM_CODIGOBARRASPRODSERV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_COMPRA> INFM_COMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_COR> INFM_COR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_CRM> INFM_CRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_GRUPOPERMISSAO> INFM_GRUPOPERMISSAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_GRUPOPRODUTO> INFM_GRUPOPRODUTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PRODUTOMARCA> INFM_PRODUTOMARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PRODCATEGORIA> INFM_PRODCATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PRODUTODERIVACAO> INFM_PRODUTODERIVACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PRODUTOSERVICO> INFM_PRODUTOSERVICO { get; set; }
        public virtual INFM_LICENCA INFM_LICENCA { get; set; }
        public virtual INFM_PESSOA INFM_PESSOA { get; set; }
        public virtual INFM_PUBLICIDADE INFM_PUBLICIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_FILIAL> INFM_FILIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_FORMAPAGAMENTO> INFM_FORMAPAGAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_GRUPOCOMPROMISSO> INFM_GRUPOCOMPROMISSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_INTEGRACAOAPI> INFM_INTEGRACAOAPI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_OBSERVACAO> INFM_OBSERVACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PARAMETROVALOR> INFM_PARAMETROVALOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PESSOA> INFM_PESSOA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PRODUTOPROMOCAO> INFM_PRODUTOPROMOCAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PRODUTONCM> INFM_PRODUTONCM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PROPOSTA> INFM_PROPOSTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PRODUTONUMEROSERIE> INFM_PRODUTONUMEROSERIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_SEGMENTOCOMERCIAL> INFM_SEGMENTOCOMERCIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_SETOREMPRESA> INFM_SETOREMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_STATUS_CRM> INFM_STATUS_CRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_STATUSCRMAGRUP> INFM_STATUSCRMAGRUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_TIPOCRM> INFM_TIPOCRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_TIPOEMPREGADO> INFM_TIPOEMPREGADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_UNIDADEMEDIDA> INFM_UNIDADEMEDIDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_VENDA> INFM_VENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PRODUTOCST> INFM_PRODUTOCST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PRODUTOCFOP> INFM_PRODUTOCFOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PROCESSO> INFM_PROCESSO { get; set; }
    }
}
