//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_PERGUNTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_PERGUNTAS()
        {
            this.INFM_PERGUNTAOPCAO = new HashSet<INFM_PERGUNTAOPCAO>();
            this.INFM_RESPOSTAPERGUNTA = new HashSet<INFM_RESPOSTAPERGUNTA>();
        }
    
        public string IDPERGUNTA { get; set; }
        public string IDGRUPOCOMPROMISSO { get; set; }
        public string DESPERGUNTA { get; set; }
        public bool BOLOBRIGATORIA { get; set; }
        public string CODTIPOCOMPONENTE { get; set; }
        public bool BOLNUMERICO { get; set; }
    
        public virtual INFM_GRUPOCOMPROMISSO INFM_GRUPOCOMPROMISSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PERGUNTAOPCAO> INFM_PERGUNTAOPCAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_RESPOSTAPERGUNTA> INFM_RESPOSTAPERGUNTA { get; set; }
    }
}
