//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_MESAVENDA
    {
        public string IDMESAVENDA { get; set; }
        public string IDMESA { get; set; }
        public string IDVENDA { get; set; }
    
        public virtual INFM_MESA INFM_MESA { get; set; }
        public virtual INFM_VENDA INFM_VENDA { get; set; }
    }
}
