//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_DATOSCOMPRAPROD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_DATOSCOMPRAPROD()
        {
            this.INFM_PRODUTOPROMOCAOPRODF = new HashSet<INFM_PRODUTOPROMOCAOPRODF>();
            this.INFM_PRODUTONUMEROSERIE = new HashSet<INFM_PRODUTONUMEROSERIE>();
        }
    
        public string IDDATOSCOMPRAPROD { get; set; }
        public string IDUNIDADEMEDIDA { get; set; }
        public string IDPRODUTOFILIAL { get; set; }
        public Nullable<decimal> NUMUNIDADECOMPRA { get; set; }
        public decimal NUMVALORCOMPRA { get; set; }
        public Nullable<decimal> NUMESTOQUE { get; set; }
        public string CODLOTE { get; set; }
        public Nullable<System.DateTime> DTHVALIDADE { get; set; }
        public string IDCOMPRA { get; set; }
        public string IDUNIDADEMEDIDAVALORCOMPRA { get; set; }
        public Nullable<decimal> NUMCSTICMS { get; set; }
        public Nullable<decimal> NUMPERCENTICMS { get; set; }
        public Nullable<decimal> NUMPERCENTBCICMS { get; set; }
        public Nullable<decimal> NUMBCST { get; set; }
        public Nullable<decimal> NUMPERCENTIPI { get; set; }
        public Nullable<decimal> NUMIPI { get; set; }
        public Nullable<decimal> NUMCFOP { get; set; }
        public Nullable<decimal> NUMICMS { get; set; }
        public Nullable<decimal> NUMBCICMS { get; set; }
        public Nullable<decimal> NUMICMSST { get; set; }
        public Nullable<decimal> NUMCSTIPI { get; set; }
        public Nullable<bool> BOLESTOQUEATUAL { get; set; }
    
        public virtual INFM_COMPRA INFM_COMPRA { get; set; }
        public virtual INFM_PRODUTOFILIAL INFM_PRODUTOFILIAL { get; set; }
        public virtual INFM_UNIDADEMEDIDA INFM_UNIDADEMEDIDA { get; set; }
        public virtual INFM_UNIDADEMEDIDA INFM_UNIDADEMEDIDA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PRODUTOPROMOCAOPRODF> INFM_PRODUTOPROMOCAOPRODF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PRODUTONUMEROSERIE> INFM_PRODUTONUMEROSERIE { get; set; }
    }
}
