//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_PESSOAMESA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_PESSOAMESA()
        {
            this.INFM_PESSOAMESAXMESA = new HashSet<INFM_PESSOAMESAXMESA>();
        }
    
        public string IDPESSOAMESA { get; set; }
        public string IDPESSOA { get; set; }
        public System.DateTime DTHLIMITE { get; set; }
        public string CODESTADO { get; set; }
    
        public virtual INFM_PESSOA INFM_PESSOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PESSOAMESAXMESA> INFM_PESSOAMESAXMESA { get; set; }
    }
}
