//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_TIPOCRM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_TIPOCRM()
        {
            this.INFM_CRM = new HashSet<INFM_CRM>();
            this.INFM_INTEGRACAOAPI = new HashSet<INFM_INTEGRACAOAPI>();
            this.INFM_TIPOCRMCONFIG = new HashSet<INFM_TIPOCRMCONFIG>();
        }
    
        public string IDTIPOCRM { get; set; }
        public string IDEMPRESA { get; set; }
        public string DESTIPOCRM { get; set; }
        public string IDSTATUSCRMAGRUP { get; set; }
        public string IDSTATUSCRM { get; set; }
        public string CODTIPOCRM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_CRM> INFM_CRM { get; set; }
        public virtual INFM_EMPRESA INFM_EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_INTEGRACAOAPI> INFM_INTEGRACAOAPI { get; set; }
        public virtual INFM_STATUS_CRM INFM_STATUS_CRM { get; set; }
        public virtual INFM_STATUSCRMAGRUP INFM_STATUSCRMAGRUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_TIPOCRMCONFIG> INFM_TIPOCRMCONFIG { get; set; }
    }
}
