//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_GRUPOPARAMETRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_GRUPOPARAMETRO()
        {
            this.INFM_PARAMETROS = new HashSet<INFM_PARAMETROS>();
        }
    
        public string IDGRUPOPARAMETRO { get; set; }
        public string CODGRUPOPARAMETRO { get; set; }
        public string DESGRUPOPARAMETRO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PARAMETROS> INFM_PARAMETROS { get; set; }
    }
}
