//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_PRODUTODERIVACAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_PRODUTODERIVACAO()
        {
            this.INFM_PRODUTOSERVICO = new HashSet<INFM_PRODUTOSERVICO>();
        }
    
        public string IDPRODUTODERIVACAO { get; set; }
        public string IDEMPRESA { get; set; }
        public int CODPRODUTODERIVACAO { get; set; }
        public string DESPRODUTODERIVACAO { get; set; }
    
        public virtual INFM_EMPRESA INFM_EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PRODUTOSERVICO> INFM_PRODUTOSERVICO { get; set; }
    }
}
