//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_PARAMETROVALOR
    {
        public string IDPARAMETROVALOR { get; set; }
        public string IDPARAMETRO { get; set; }
        public string IDFILIAL { get; set; }
        public string DESVALORPARAMETRO { get; set; }
        public string IDEMPRESA { get; set; }
    
        public virtual INFM_EMPRESA INFM_EMPRESA { get; set; }
        public virtual INFM_FILIAL INFM_FILIAL { get; set; }
        public virtual INFM_PARAMETROS INFM_PARAMETROS { get; set; }
    }
}
