//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_TIPOPESSOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_TIPOPESSOA()
        {
            this.INFM_TIPOPESSOA_PESSOA = new HashSet<INFM_TIPOPESSOA_PESSOA>();
        }
    
        public string IDTIPOPESSOA { get; set; }
        public string DESTIPOPESSOA { get; set; }
        public int CODTIPOPESSOA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_TIPOPESSOA_PESSOA> INFM_TIPOPESSOA_PESSOA { get; set; }
    }
}
