//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_PRODUTOPROMOCAOPRODF
    {
        public string IDPRODUTOPROMOCAOPRODF { get; set; }
        public string IDPRODUTOPROMOCAO { get; set; }
        public string IDPRODUTOFILIAL { get; set; }
        public string IDDATOSCOMPRAPROD { get; set; }
        public string IDPRODUTOSERVICO { get; set; }
    
        public virtual INFM_DATOSCOMPRAPROD INFM_DATOSCOMPRAPROD { get; set; }
        public virtual INFM_PRODUTOFILIAL INFM_PRODUTOFILIAL { get; set; }
        public virtual INFM_PRODUTOPROMOCAO INFM_PRODUTOPROMOCAO { get; set; }
        public virtual INFM_PRODUTOSERVICO INFM_PRODUTOSERVICO { get; set; }
    }
}
