//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_GRUPOPRODUTOSUBGRUPO
    {
        public string IDGRUPOPRODUTOSUBGRUPO { get; set; }
        public string IDGRUPOPRODUTOPAI { get; set; }
        public string IDGRUPOPRODUTO { get; set; }
    
        public virtual INFM_GRUPOPRODUTO INFM_GRUPOPRODUTO { get; set; }
        public virtual INFM_GRUPOPRODUTO INFM_GRUPOPRODUTO1 { get; set; }
    }
}
