//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_PARAMETROS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_PARAMETROS()
        {
            this.INFM_PARAMETROOPCAO = new HashSet<INFM_PARAMETROOPCAO>();
            this.INFM_PARAMETROVALOR = new HashSet<INFM_PARAMETROVALOR>();
        }
    
        public string IDPARAMETRO { get; set; }
        public string CODPARAMETRO { get; set; }
        public string DESPARAMETRO { get; set; }
        public int TIPOCOMPONENTE { get; set; }
        public bool BOLNIVELFILIAL { get; set; }
        public string IDGRUPOPARAMETRO { get; set; }
    
        public virtual INFM_GRUPOPARAMETRO INFM_GRUPOPARAMETRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PARAMETROOPCAO> INFM_PARAMETROOPCAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PARAMETROVALOR> INFM_PARAMETROVALOR { get; set; }
    }
}
