//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_PARAMETROOPCAO
    {
        public string IDPARAMETROOPCAO { get; set; }
        public string IDPARAMETRO { get; set; }
        public string CODPARAMETROOPCAO { get; set; }
        public string DESPARAMETROOPCAO { get; set; }
    
        public virtual INFM_PARAMETROS INFM_PARAMETROS { get; set; }
    }
}
