//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_PRODUTOCOMISSAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_PRODUTOCOMISSAO()
        {
            this.INFM_PRODUTOFILIAL = new HashSet<INFM_PRODUTOFILIAL>();
        }
    
        public string IDPRODUTOCOMISSAO { get; set; }
        public string IDFILIAL { get; set; }
        public int CODPRODUTOCOMISSAO { get; set; }
        public string DESPRODUTOCOMISSAO { get; set; }
        public Nullable<decimal> NUMCOMISSAOPER { get; set; }
        public Nullable<decimal> NUMCOMISSAOVALOR { get; set; }
        public Nullable<bool> BOLHABILITADA { get; set; }
    
        public virtual INFM_FILIAL INFM_FILIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PRODUTOFILIAL> INFM_PRODUTOFILIAL { get; set; }
    }
}
