//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_CRM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_CRM()
        {
            this.INFM_PESSOACRM = new HashSet<INFM_PESSOACRM>();
            this.INFM_PROPOSTA = new HashSet<INFM_PROPOSTA>();
        }
    
        public string IDCRM { get; set; }
        public string IDEMPRESA { get; set; }
        public string IDGRUPOCOMPROMISSO { get; set; }
        public string IDPESSOACADASTRO { get; set; }
        public string IDPESSOACLIENTE { get; set; }
        public int CODCRM { get; set; }
        public string OBSCOMPROMISSO { get; set; }
        public string DESCRM { get; set; }
        public bool BOLATIVO { get; set; }
        public string IDSTATUSCRM { get; set; }
        public string IDTIPOCRM { get; set; }
    
        public virtual INFM_PESSOA INFM_PESSOA { get; set; }
        public virtual INFM_TIPOCRM INFM_TIPOCRM { get; set; }
        public virtual INFM_EMPRESA INFM_EMPRESA { get; set; }
        public virtual INFM_PESSOA INFM_PESSOA1 { get; set; }
        public virtual INFM_STATUS_CRM INFM_STATUS_CRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PESSOACRM> INFM_PESSOACRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PROPOSTA> INFM_PROPOSTA { get; set; }
    }
}
