//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_SANGRIA
    {
        public string IDSANGRIA { get; set; }
        public string IDRESPONSAVELCAIXA { get; set; }
        public string IDPESSOASUPERVISOR { get; set; }
        public decimal NUMVALORSANGRIA { get; set; }
        public string OBSSANGRIA { get; set; }
    
        public virtual INFM_PESSOA INFM_PESSOA { get; set; }
        public virtual INFM_RESPONSAVELCAIXA INFM_RESPONSAVELCAIXA { get; set; }
    }
}
