//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_TIPODOCUMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_TIPODOCUMENTO()
        {
            this.INFM_DOCUMENTO = new HashSet<INFM_DOCUMENTO>();
        }
    
        public string IDTIPODOCUMENTO { get; set; }
        public string CODTIPODOCUMENTO { get; set; }
        public string DESTIPODOCUMENTO { get; set; }
        public Nullable<bool> BOLCREDITO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_DOCUMENTO> INFM_DOCUMENTO { get; set; }
    }
}
