//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_TRANSACOES
    {
        public string IDTRANSACAO { get; set; }
        public string IDDOCUMENTO { get; set; }
        public string IDPARCELAMENTO { get; set; }
        public Nullable<decimal> NUMVALORACRESCIMO { get; set; }
        public Nullable<decimal> NUMVALORDESCONTO { get; set; }
        public decimal NUMVALORTRANSACAO { get; set; }
        public System.DateTime DTHTRANSACAO { get; set; }
    
        public virtual INFM_DOCUMENTO INFM_DOCUMENTO { get; set; }
        public virtual INFM_PARCELAMENTO INFM_PARCELAMENTO { get; set; }
    }
}
