//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_FILIAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_FILIAL()
        {
            this.INFM_CAIXA = new HashSet<INFM_CAIXA>();
            this.INFM_CAIXA1 = new HashSet<INFM_CAIXA>();
            this.INFM_COMPRA = new HashSet<INFM_COMPRA>();
            this.INFM_DOCUMENTO = new HashSet<INFM_DOCUMENTO>();
            this.INFM_PRODUTOFILIAL = new HashSet<INFM_PRODUTOFILIAL>();
            this.INFM_PRODUTOCOMISSAO = new HashSet<INFM_PRODUTOCOMISSAO>();
            this.INFM_FILIALBAIRRO = new HashSet<INFM_FILIALBAIRRO>();
            this.INFM_FILIALPESSOA = new HashSet<INFM_FILIALPESSOA>();
            this.INFM_MESA = new HashSet<INFM_MESA>();
            this.INFM_PARAMETROVALOR = new HashSet<INFM_PARAMETROVALOR>();
            this.INFM_PRODUTOPROMOCAO = new HashSet<INFM_PRODUTOPROMOCAO>();
            this.INFM_SALDOFILIAL = new HashSet<INFM_SALDOFILIAL>();
            this.INFM_SESSAO = new HashSet<INFM_SESSAO>();
            this.INFM_SETOREMPRESA = new HashSet<INFM_SETOREMPRESA>();
            this.INFM_VENDA = new HashSet<INFM_VENDA>();
        }
    
        public string IDFILIAL { get; set; }
        public string IDEMPRESA { get; set; }
        public string IDENDERECO { get; set; }
        public string IDPESSOA { get; set; }
        public int CODFILIAL { get; set; }
        public string DESFILIAL { get; set; }
        public bool BOLMATRIZ { get; set; }
        public Nullable<int> NUMENDERECO { get; set; }
        public string DESCOMPENDERECO { get; set; }
        public string DESPONTREFENDERECO { get; set; }
        public Nullable<System.DateTime> DTHABERTURA { get; set; }
        public string DESTELEFONEFIXO { get; set; }
        public string DESTELEFONEFAX { get; set; }
        public string DESTELEFONECEL { get; set; }
        public string OBSFILIAL { get; set; }
        public string DESEMAIL { get; set; }
        public Nullable<decimal> NUMPISPER { get; set; }
        public Nullable<decimal> NUMCONFINSPER { get; set; }
        public Nullable<decimal> NUMOUTDESPPER { get; set; }
        public Nullable<decimal> NUMCONTSOCPER { get; set; }
        public Nullable<int> CODTABMERCADORIA { get; set; }
        public bool BOLATIVA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_CAIXA> INFM_CAIXA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_CAIXA> INFM_CAIXA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_COMPRA> INFM_COMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_DOCUMENTO> INFM_DOCUMENTO { get; set; }
        public virtual INFM_EMPRESA INFM_EMPRESA { get; set; }
        public virtual INFM_ENDERECO INFM_ENDERECO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PRODUTOFILIAL> INFM_PRODUTOFILIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PRODUTOCOMISSAO> INFM_PRODUTOCOMISSAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_FILIALBAIRRO> INFM_FILIALBAIRRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_FILIALPESSOA> INFM_FILIALPESSOA { get; set; }
        public virtual INFM_PESSOA INFM_PESSOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_MESA> INFM_MESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PARAMETROVALOR> INFM_PARAMETROVALOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PRODUTOPROMOCAO> INFM_PRODUTOPROMOCAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_SALDOFILIAL> INFM_SALDOFILIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_SESSAO> INFM_SESSAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_SETOREMPRESA> INFM_SETOREMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_VENDA> INFM_VENDA { get; set; }
    }
}
