//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_PAGAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_PAGAMENTO()
        {
            this.INFM_ITEMVENDA = new HashSet<INFM_ITEMVENDA>();
        }
    
        public string IDPAGAMENTO { get; set; }
        public string IDVENDA { get; set; }
        public string IDFORMAPAGAMENTO { get; set; }
        public decimal NUMVALOR { get; set; }
        public string IDRESPONSAVELCAIXA { get; set; }
    
        public virtual INFM_FORMAPAGAMENTO INFM_FORMAPAGAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_ITEMVENDA> INFM_ITEMVENDA { get; set; }
        public virtual INFM_VENDA INFM_VENDA { get; set; }
        public virtual INFM_RESPONSAVELCAIXA INFM_RESPONSAVELCAIXA { get; set; }
    }
}
