//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_RESPOSTAPERGUNTA
    {
        public string IDRESPOSTAPERGUNTA { get; set; }
        public string IDPERGUNTA { get; set; }
        public string DESVALOR { get; set; }
        public string IDPESSOACRM { get; set; }
    
        public virtual INFM_PERGUNTAS INFM_PERGUNTAS { get; set; }
        public virtual INFM_PESSOACRM INFM_PESSOACRM { get; set; }
    }
}
