//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_DIASEMANAPROMOCAO
    {
        public string IDDIASEMANAPROMOCAO { get; set; }
        public string IDPRODUTOPROMOCAO { get; set; }
        public string CODDIASEMANA { get; set; }
    
        public virtual INFM_PRODUTOPROMOCAO INFM_PRODUTOPROMOCAO { get; set; }
    }
}
