//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_ITEMPROCESSO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_ITEMPROCESSO()
        {
            this.INFM_ITEMPROCESSOERRO = new HashSet<INFM_ITEMPROCESSOERRO>();
        }
    
        public string IDITEMPROCESSO { get; set; }
        public string IDPROCESSO { get; set; }
        public string DESVALOR { get; set; }
        public System.DateTime DTHCRIACAO { get; set; }
        public Nullable<System.DateTime> DTHEXECUCAO { get; set; }
        public Nullable<int> NELTENTATIVAS { get; set; }
        public bool BOLCONCLUIDO { get; set; }
        public System.DateTime DTHPROGRAMADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_ITEMPROCESSOERRO> INFM_ITEMPROCESSOERRO { get; set; }
        public virtual INFM_PROCESSO INFM_PROCESSO { get; set; }
    }
}
