//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_GRUPOPERMISSAOACAO
    {
        public string IDGRUPOPERMISSAOACAO { get; set; }
        public string IDPERMISSAO { get; set; }
        public string IDACAO { get; set; }
        public string IDGRUPOPERMISSAO { get; set; }
    
        public virtual INFM_ACAO INFM_ACAO { get; set; }
        public virtual INFM_GRUPOPERMISSAO INFM_GRUPOPERMISSAO { get; set; }
        public virtual INFM_PERMISSAO INFM_PERMISSAO { get; set; }
    }
}
