//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_FORMAPAGAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_FORMAPAGAMENTO()
        {
            this.INFM_DOCUMENTO = new HashSet<INFM_DOCUMENTO>();
            this.INFM_PAGAMENTO = new HashSet<INFM_PAGAMENTO>();
            this.INFM_VALORFECHAMENTO = new HashSet<INFM_VALORFECHAMENTO>();
        }
    
        public string IDFORMAPAGAMENTO { get; set; }
        public string DESFORMAPAGAMENTO { get; set; }
        public string CODFORMAPAGAMENTO { get; set; }
        public Nullable<decimal> NUMVALORDESCONTO { get; set; }
        public Nullable<decimal> NUMPERCENTDESCONTO { get; set; }
        public Nullable<decimal> NUMVALORACRESCIMO { get; set; }
        public Nullable<decimal> NUMPERCENTACRESCIMO { get; set; }
        public Nullable<bool> BOLCARTAO { get; set; }
        public Nullable<bool> BOLCREDITO { get; set; }
        public string IDEMPRESA { get; set; }
        public string CODTIPOPAGAMENTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_DOCUMENTO> INFM_DOCUMENTO { get; set; }
        public virtual INFM_EMPRESA INFM_EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PAGAMENTO> INFM_PAGAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_VALORFECHAMENTO> INFM_VALORFECHAMENTO { get; set; }
    }
}
