//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_PRODUTOPROMOCAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_PRODUTOPROMOCAO()
        {
            this.INFM_DIASEMANAPROMOCAO = new HashSet<INFM_DIASEMANAPROMOCAO>();
            this.INFM_PRODUTOPROMOCAOPRODF = new HashSet<INFM_PRODUTOPROMOCAOPRODF>();
        }
    
        public string IDPRODUTOPROMOCAO { get; set; }
        public int CODPRODUTOPROMOCAO { get; set; }
        public string DESPRODUTOPROMOCAO { get; set; }
        public Nullable<decimal> NUMPROMOCAOPER { get; set; }
        public Nullable<decimal> NUMPROMOCAOVALOR { get; set; }
        public bool BOLHABILITADA { get; set; }
        public System.DateTime DTHINICIO { get; set; }
        public System.DateTime DTHFIM { get; set; }
        public string CODTIPOPROMOCAO { get; set; }
        public string IDEMPRESA { get; set; }
        public string IDFILIAL { get; set; }
        public Nullable<bool> BOL_POR_HORARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_DIASEMANAPROMOCAO> INFM_DIASEMANAPROMOCAO { get; set; }
        public virtual INFM_EMPRESA INFM_EMPRESA { get; set; }
        public virtual INFM_FILIAL INFM_FILIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PRODUTOPROMOCAOPRODF> INFM_PRODUTOPROMOCAOPRODF { get; set; }
    }
}
