//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_TIPOEMPREGADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_TIPOEMPREGADO()
        {
            this.INFM_PESSOA = new HashSet<INFM_PESSOA>();
            this.INFM_TIPOCRMCONFIG = new HashSet<INFM_TIPOCRMCONFIG>();
        }
    
        public string IDTIPOEMPREGADO { get; set; }
        public string IDEMPRESA { get; set; }
        public string DESTIPOEMPREGADO { get; set; }
        public Nullable<bool> BOLSUPERVISOR { get; set; }
        public Nullable<bool> BOLRECEBEREMAILVENDA { get; set; }
        public Nullable<bool> BOLENTREGADOR { get; set; }
        public Nullable<bool> BOLRESPFINANCEIRO { get; set; }
        public Nullable<bool> BOLGERENTE { get; set; }
        public Nullable<bool> BOLENVIAREMAILFECHAMENTO { get; set; }
    
        public virtual INFM_EMPRESA INFM_EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PESSOA> INFM_PESSOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_TIPOCRMCONFIG> INFM_TIPOCRMCONFIG { get; set; }
    }
}
