//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_VENDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_VENDA()
        {
            this.INFM_ITEMVENDA = new HashSet<INFM_ITEMVENDA>();
            this.INFM_MESAVENDA = new HashSet<INFM_MESAVENDA>();
            this.INFM_PAGAMENTO = new HashSet<INFM_PAGAMENTO>();
        }
    
        public string IDFILIAL { get; set; }
        public string IDVENDA { get; set; }
        public string IDPESSOACLIENTE { get; set; }
        public string IDRESPONSAVELCAIXA { get; set; }
        public string IDPESSOAENTREGADOR { get; set; }
        public string IDENDERECOENTREGA { get; set; }
        public string IDEMPRESA { get; set; }
        public System.DateTime DTHVENDAINICIO { get; set; }
        public Nullable<System.DateTime> DTHVENDAFIM { get; set; }
        public Nullable<decimal> NUMVALORSERVICO { get; set; }
        public Nullable<decimal> NUMVALORTAXAENTREGA { get; set; }
        public string COD_ESTADO { get; set; }
        public Nullable<decimal> NUMDESCONTO { get; set; }
        public decimal NUMVALORVENDA { get; set; }
        public decimal NUMVALORTOTAL { get; set; }
        public string CODCOMANDA { get; set; }
        public string CODESTADOVENDA { get; set; }
        public Nullable<int> NUMQUANTIDADEPESSOAS { get; set; }
        public string OBSVENDA { get; set; }
        public string IDPESSOACANCELAMENTO { get; set; }
        public int CODVENDA { get; set; }
        public Nullable<decimal> NUMTROCO { get; set; }
        public Nullable<decimal> NUMACRESCIMO { get; set; }
        public string IDPESSOAVENDA { get; set; }
    
        public virtual INFM_EMPRESA INFM_EMPRESA { get; set; }
        public virtual INFM_ENDERECO INFM_ENDERECO { get; set; }
        public virtual INFM_FILIAL INFM_FILIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_ITEMVENDA> INFM_ITEMVENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_MESAVENDA> INFM_MESAVENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PAGAMENTO> INFM_PAGAMENTO { get; set; }
        public virtual INFM_PESSOA INFM_PESSOA { get; set; }
        public virtual INFM_PESSOA INFM_PESSOA1 { get; set; }
        public virtual INFM_PESSOA INFM_PESSOA2 { get; set; }
        public virtual INFM_RESPONSAVELCAIXA INFM_RESPONSAVELCAIXA { get; set; }
        public virtual INFM_PESSOA INFM_PESSOA21 { get; set; }
    }
}
