//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_ITEMPROCESSOERRO
    {
        public string IDITEMPROCESSOERRO { get; set; }
        public string IDITEMPROCESSO { get; set; }
        public string DESERRO { get; set; }
        public Nullable<System.DateTime> DTHERRO { get; set; }
        public string IDPROCESSO { get; set; }
    
        public virtual INFM_ITEMPROCESSO INFM_ITEMPROCESSO { get; set; }
        public virtual INFM_PROCESSO INFM_PROCESSO { get; set; }
    }
}
