//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_COMPRA()
        {
            this.INFM_DATOSCOMPRAPROD = new HashSet<INFM_DATOSCOMPRAPROD>();
        }
    
        public string IDCOMPRA { get; set; }
        public string IDFORNECEDOR { get; set; }
        public string IDEMPRESA { get; set; }
        public string IDFILIAL { get; set; }
        public string CODCOMPRA { get; set; }
        public System.DateTime DTHCOMPRA { get; set; }
        public string CODESTADO { get; set; }
        public string OBSCOMPRA { get; set; }
        public string CODNOTAFISCAL { get; set; }
        public string CODRASTREIO { get; set; }
        public Nullable<System.DateTime> DTHRECEBIMENTO { get; set; }
        public Nullable<decimal> NUMBASECALCULO { get; set; }
        public Nullable<decimal> NUMICMS { get; set; }
        public Nullable<decimal> NUMBASESUBSTITUICAO { get; set; }
        public Nullable<decimal> NUMICMSSUBSTITUICAO { get; set; }
        public Nullable<decimal> NUMFRETE { get; set; }
        public Nullable<decimal> NUMSEGURO { get; set; }
        public Nullable<decimal> NUMOUTRASDESPESAS { get; set; }
        public Nullable<decimal> NUMDESCONTO { get; set; }
        public string OBSOUTRASINFORMACOES { get; set; }
        public Nullable<int> QTDVOLUMES { get; set; }
        public string DESESPECIE { get; set; }
        public string DESMARCA { get; set; }
        public Nullable<int> NUMVOLUMES { get; set; }
        public Nullable<decimal> NUMPESOBRUTO { get; set; }
        public Nullable<decimal> NUMPESOLIQUIDO { get; set; }
        public Nullable<decimal> NUMVALORTOTALIPI { get; set; }
    
        public virtual INFM_EMPRESA INFM_EMPRESA { get; set; }
        public virtual INFM_FILIAL INFM_FILIAL { get; set; }
        public virtual INFM_PESSOA INFM_PESSOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_DATOSCOMPRAPROD> INFM_DATOSCOMPRAPROD { get; set; }
    }
}
