//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_UNIDADEMEDIDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_UNIDADEMEDIDA()
        {
            this.INFM_DATOSCOMPRAPROD = new HashSet<INFM_DATOSCOMPRAPROD>();
            this.INFM_DATOSCOMPRAPROD1 = new HashSet<INFM_DATOSCOMPRAPROD>();
            this.INFM_PRODUTOFILIAL = new HashSet<INFM_PRODUTOFILIAL>();
            this.INFM_PRODUTOFILIAL1 = new HashSet<INFM_PRODUTOFILIAL>();
            this.INFM_PRODUTOFILIAL2 = new HashSet<INFM_PRODUTOFILIAL>();
            this.INFM_UNIDADEMEDPRODUTO = new HashSet<INFM_UNIDADEMEDPRODUTO>();
            this.INFM_UNIDADEMEDIDA1 = new HashSet<INFM_UNIDADEMEDIDA>();
        }
    
        public string IDUNIDADEMEDIDA { get; set; }
        public string IDUNIDADEMEDIDAPAI { get; set; }
        public string IDEMPRESA { get; set; }
        public string CODUNIDADEMEDIDA { get; set; }
        public Nullable<decimal> NUMUNIDADEPAI { get; set; }
        public string DESUNIDADEMEDIDA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_DATOSCOMPRAPROD> INFM_DATOSCOMPRAPROD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_DATOSCOMPRAPROD> INFM_DATOSCOMPRAPROD1 { get; set; }
        public virtual INFM_EMPRESA INFM_EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PRODUTOFILIAL> INFM_PRODUTOFILIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PRODUTOFILIAL> INFM_PRODUTOFILIAL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PRODUTOFILIAL> INFM_PRODUTOFILIAL2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_UNIDADEMEDPRODUTO> INFM_UNIDADEMEDPRODUTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_UNIDADEMEDIDA> INFM_UNIDADEMEDIDA1 { get; set; }
        public virtual INFM_UNIDADEMEDIDA INFM_UNIDADEMEDIDA2 { get; set; }
    }
}
