//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_PRODUTOOPCAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_PRODUTOOPCAO()
        {
            this.INFM_PRODUTOFILIAL = new HashSet<INFM_PRODUTOFILIAL>();
        }
    
        public string IDPRODUTOOPCAO { get; set; }
        public string IDPRODUTOSERVICO { get; set; }
        public string CODPRODUTOOPCAO { get; set; }
        public string DESPRODUTOOPCAO { get; set; }
        public string DESCODBARRAS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_PRODUTOFILIAL> INFM_PRODUTOFILIAL { get; set; }
        public virtual INFM_PRODUTOSERVICO INFM_PRODUTOSERVICO { get; set; }
    }
}
