//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_LICENCA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_LICENCA()
        {
            this.INFM_EMPRESA = new HashSet<INFM_EMPRESA>();
        }
    
        public string IDLICENCA { get; set; }
        public string CODLICENCA { get; set; }
        public bool SESSOESINFINITAS { get; set; }
        public int NUMQUANTIDADESESSOES { get; set; }
        public Nullable<int> NUMVALIDADE { get; set; }
        public bool VALIDADEINFINITA { get; set; }
        public bool CHAVEATIVA { get; set; }
        public Nullable<int> NUMQUANTIDADEACESSOS { get; set; }
        public Nullable<System.DateTime> DATAATIVACAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_EMPRESA> INFM_EMPRESA { get; set; }
    }
}
