//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_ESTADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_ESTADO()
        {
            this.INFM_CIDADE = new HashSet<INFM_CIDADE>();
        }
    
        public string IDESTADO { get; set; }
        public string CODESTADO { get; set; }
        public string DESESTADO { get; set; }
        public Nullable<decimal> NUMICMS { get; set; }
        public string CODIBGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_CIDADE> INFM_CIDADE { get; set; }
    }
}
