//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informatiz.ControleEstoque.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFM_PROCESSO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFM_PROCESSO()
        {
            this.INFM_ITEMPROCESSO = new HashSet<INFM_ITEMPROCESSO>();
            this.INFM_ITEMPROCESSOERRO = new HashSet<INFM_ITEMPROCESSOERRO>();
        }
    
        public string IDPROCESSO { get; set; }
        public string IDEMPRESA { get; set; }
        public bool BOLATIVO { get; set; }
        public string CODTIPOPROCESSO { get; set; }
        public int NELINTERVALO { get; set; }
        public int NELTENTATIVAS { get; set; }
        public string DESPROCESSO { get; set; }
    
        public virtual INFM_EMPRESA INFM_EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_ITEMPROCESSO> INFM_ITEMPROCESSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFM_ITEMPROCESSOERRO> INFM_ITEMPROCESSOERRO { get; set; }
    }
}
