QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'MT'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('12',
             'MT',
             'MATO GROSSO')