QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'MG'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('14',
             'MG',
             'MINAS GERAIS')