QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'PI'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('19',
             'PI',
             'PIAUÍ')