QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'RN'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('21',
             'RN',
             'RIO GRANDE DO NORTE')