QUERYVALIDACAO select 1 FROM INFM_SITUACAO_PESSOA WHERE CODSITUACAO = 'F'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_SITUACAO_PESSOA
            (IDSITUACAOPESSOA,
			 DESSITUACAO,
			 CODSITUACAO)
	  VALUES
	        ('4',
			 'Cheque Devolvido',
			 'F')