QUERYVALIDACAO SELECT 1 FROM SYS.TABLES AS T JOIN SYS.COLUMNS AS C ON T.OBJECT_ID = C.OBJECT_ID WHERE T.TYPE = 'U' AND T.NAME = 'INFM_SEGMENTOCOMERCIAL' AND C.NAME = 'IDEMPRESA'
BANCODEDADOS INFORMATIZ
ALTER TABLE INFM_SEGMENTOCOMERCIAL ADD IDEMPRESA OBJETOID NULL