QUERYVALIDACAO select 1 FROM INFM_PERMISSAO WHERE CODPERMISSAO = 'SEGMENTOCOMERCIAL'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_PERMISSAO
           (IDPERMISSAO
           ,CODPERMISSAO
           ,DESPERMISSAO
		   ,BOLOBRIGATORIA)
     VALUES
           ('23'
           ,'SEGMENTOCOMERCIAL'
           ,'Tela Cadastro de Segmento Comercial'
		   ,0)