QUERYVALIDACAO select 1 FROM INFM_TIPODOCUMENTO WHERE CODTIPODOCUMENTO = 'D'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_TIPODOCUMENTO
           (IDTIPODOCUMENTO
           ,CODTIPODOCUMENTO
           ,DESTIPODOCUMENTO)
     VALUES
           ('3'
           ,'D'
           ,'Duplicata')