QUERYVALIDACAO select 1 FROM INFM_LOCALDOCUMENTO WHERE CODLOCALDOCUMENTO = 'E'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_LOCALDOCUMENTO
           (IDLOCALDOCUMENTO
           ,CODLOCALDOCUMENTO
           ,DESLOCALDOCUMENTO)
     VALUES
           ('1'
           ,'E'
           ,'Empresa')