QUERYVALIDACAO select 1 FROM INFM_LOCALDOCUMENTO WHERE CODLOCALDOCUMENTO = 'V'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_LOCALDOCUMENTO
           (IDLOCALDOCUMENTO
           ,CODLOCALDOCUMENTO
           ,DESLOCALDOCUMENTO)
     VALUES
           ('2'
           ,'V'
           ,'Vendedor')