QUERYVALIDACAO select 1 FROM INFM_FORMAPAGAMENTO WHERE CODFORMAPAGAMENTO = 'D'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_FORMAPAGAMENTO
           (IDFORMAPAGAMENTO
           ,DESFORMAPAGAMENTO
           ,CODFORMAPAGAMENTO)
     VALUES
           ('1'
           ,'Dinheiro'
           ,'D')