QUERYVALIDACAO select 1 FROM INFM_FORMAPAGAMENTO WHERE CODFORMAPAGAMENTO = 'P'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_FORMAPAGAMENTO
           (IDFORMAPAGAMENTO
           ,DESFORMAPAGAMENTO
           ,CODFORMAPAGAMENTO)
     VALUES
           ('4'
           ,'Cheque Pre Datado'
           ,'P')