QUERYVALIDACAO SELECT 1 FROM SYS.TABLES AS T JOIN SYS.COLUMNS AS C ON T.OBJECT_ID = C.OBJECT_ID WHERE T.TYPE = 'U' AND T.NAME = 'INFM_DOCUMENTO' AND C.NAME = 'CODDOCUMENTO'
BANCODEDADOS INFORMATIZ
ALTER TABLE INFM_DOCUMENTO ADD CODDOCUMENTO CODIGO20 not null