ALTER TABLE INFM_DOCUMENTO ADD CODDOCUMENTO CODIGO20 not null
;
create index IXPESSOACRMPESSOA1 on INFM_PESSOACRMPESSOA (IDPESSOA ASC)
;
create index IXPESSOACRM1 on INFM_PESSOACRM (DTHPROXAGENDAMENTO ASC,DTHPROXAGENDAMENTOFIN ASC)
;

