QUERYVALIDACAO select 1 FROM INFM_TIPOPESSOA WHERE CODTIPOPESSOA = 3
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_TIPOPESSOA
           (IDTIPOPESSOA
           ,DESTIPOPESSOA
           ,CODTIPOPESSOA)
     VALUES
           (3
           ,'Fornecedor'
           ,3)