QUERYVALIDACAO select 1 FROM INFM_PERMISSAOACAO WHERE IDPERMISSAO = '7' AND IDACAO = '2'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_PERMISSAOACAO
          (IDPERMISSAOACAO
           ,IDPERMISSAO
           ,IDACAO)
     VALUES
           ('20'
           ,'7'
           ,'2')