QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'AC'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('1',
             'AC',
             'ACRE')