QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'DF'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('8',
             'DF',
             'DISTRITO FEDERAL')