QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'GO'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('10',
             'GO',
             'GOIAS')