QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'PB'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('16',
             'PB',
             'PARAIBA')