QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'SP'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('27',
             'SP',
             'SÃO PAULO')