QUERYVALIDACAO select 1 FROM INFM_SITUACAO_PESSOA WHERE CODSITUACAO = 'D'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_SITUACAO_PESSOA
            (IDSITUACAOPESSOA,
			 DESSITUACAO,
			 CODSITUACAO)
	  VALUES
	        ('3',
			 'Devolução',
			 'D')