QUERYVALIDACAO select 1 FROM INFM_TIPODOCUMENTO WHERE CODTIPODOCUMENTO = 'N'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_TIPODOCUMENTO
           (IDTIPODOCUMENTO
           ,CODTIPODOCUMENTO
           ,DESTIPODOCUMENTO)
     VALUES
           ('2'
           ,'N'
           ,'Nota')