QUERYVALIDACAO select 1 FROM INFM_FORMAPAGAMENTO WHERE CODFORMAPAGAMENTO = 'A'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_FORMAPAGAMENTO
           (IDFORMAPAGAMENTO
           ,DESFORMAPAGAMENTO
           ,CODFORMAPAGAMENTO)
     VALUES
           ('3'
           ,'Cheque a Vista'
           ,'A')