QUERYVALIDACAO select 1 FROM INFM_FORMAPAGAMENTO WHERE CODFORMAPAGAMENTO = 'B'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_FORMAPAGAMENTO
           (IDFORMAPAGAMENTO
           ,DESFORMAPAGAMENTO
           ,CODFORMAPAGAMENTO)
     VALUES
           ('5'
           ,'Boleto'
           ,'B')