QUERYVALIDACAO select 1 FROM INFM_FORMAPAGAMENTO WHERE CODFORMAPAGAMENTO = 'O'
BANCODEDADOS INFORMATIZ
INSERT INTO INFM_FORMAPAGAMENTO
           (IDFORMAPAGAMENTO
           ,DESFORMAPAGAMENTO
           ,CODFORMAPAGAMENTO)
     VALUES
           ('6'
           ,'Outros'
           ,'O')