QUERYVALIDACAO SELECT 1 FROM SYS.TABLES AS T JOIN SYS.COLUMNS AS C ON T.OBJECT_ID = C.OBJECT_ID WHERE T.TYPE = 'U' AND T.NAME = 'INFM_PESSOACRM' AND C.NAME = 'DESAGENDAMENTO'
BANCODEDADOS INFORMATIZ
ALTER TABLE INFM_PESSOACRM ADD DESAGENDAMENTO DESCRICAO200 not null