QUERYVALIDACAO select 1 from  sysobjects where  id = object_id('INFM_SEGMENTOCOMERCIAL') and   type = 'U'
BANCODEDADOS INFORMATIZ
create table INFM_SEGMENTOCOMERCIAL (
   IDSEGMENTOCOMERCIAL  OBJETOID             not null,
   CODSEGMENTOCOMERCIAL INTEIROSEQ           identity,
   DESSEGMENTOCOMERCIAL DESCRICAO100         not null,
   constraint PK_INFM_SEGMENTOCOMERCIAL primary key (IDSEGMENTOCOMERCIAL))