CREATE DATABASE INFORMATIZ
;
alter table INFM_CRM
   add constraint FK_INFM_CRM_REFERENCE_INFM_GRU foreign key (IDGRUPOCOMPROMISSO)
      references INFM_GRUPOCOMPROMISSO (IDGRUPOCOMPROMISSO)
;
DELETE INFM_RESPOSTAPERGUNTA
;
DELETE INFM_PESSOACRM
;
ALTER TABLE INFM_PESSOACRM DROP CONSTRAINT FK_INFM_PES_REF_INFM_PES2
;
ALTER TABLE INFM_PESSOACRM DROP COLUMN IDPESSOA
;
create table INFM_PESSOACRMPESSOA (
   IDPESSOACRMPESSOA    OBJETO_ID            not null,
   IDPESSOACRM          OBJETO_ID            null,
   IDPESSOA             OBJETOID             null,
   constraint PK_INFM_PESSOACRMPESSOA primary key (IDPESSOACRMPESSOA))
;
alter table INFM_PESSOACRMPESSOA
   add constraint FK_INFM_PESCRM_INFM_PESCRMPES foreign key (IDPESSOACRM)
      references INFM_PESSOACRM (IDPESSOACRM)
;
alter table INFM_PESSOACRMPESSOA
   add constraint FK_INFM_PES_INFM_PESCRMPES foreign key (IDPESSOA)
      references INFM_PESSOA (IDPESSOA)
;

