SELECT PS.DESPRODUTO,
       PS.CODPRODUTO,
	   PS.DESCODBARRAS,
       F.CODFILIAL,
       F.DESFILIAL,
	   F.DESTELEFONEFIXO,
	   F.DESTELEFONEFAX,
	   F.DESTELEFONECEL,
	   F.DESEMAIL,
       CASE WHEN SUM(DCP.NUMESTOQUE) IS NULL THEN 0 ELSE SUM(DCP.NUMESTOQUE) END AS ESTOQUE
FROM INFM_PRODUTOSERVICO AS PS
INNER JOIN INFM_TIPOPRODUTO AS TP ON TP.IDTIPOPRODUTO = PS.IDTIPOPRODUTO AND TP.CODTIPOPRODUTO = 'PRODUTO'
INNER JOIN INFM_PRODUTOFILIAL AS PF ON PF.IDPRODUTOSERVICO = PS.IDPRODUTOSERVICO
INNER JOIN INFM_FILIAL AS F ON F.IDFILIAL = PF.IDFILIAL
LEFT JOIN INFM_DATOSCOMPRAPROD AS DCP ON DCP.IDPRODUTOFILIAL = PF.IDPRODUTOFILIAL
WHERE F.IDEMPRESA = @IDEMPRESA {0}
GROUP BY PS.CODPRODUTO,
		 PS.DESPRODUTO,
         PS.DESCODBARRAS,
         F.CODFILIAL,
         F.DESFILIAL,
		 F.DESTELEFONEFIXO,
	     F.DESTELEFONEFAX,
	     F.DESTELEFONECEL,
	     F.DESEMAIL