SELECT DISTINCT P.IDPESSOA
				,P.DESNOME
				,P.DESNOMEFANTASIA
				,P.DESRG
				,P.DTHNASCIMENTO
				,P.DTHADMISSAO
				,P.DESCPF
				,P.DESCNPJ
				,P.DESTELEFONEFIXO
				,P.DESTELEFONEFAX
				,P.DESTELEFONECELULAR
				,P.DESEMPRESA
				,P.BOLFUNICIONARIOATIVO
				,P.BOLFORNECEDORATIVO
				,P.DESCARGO
				,P.CODLOGIN
				,P.NUMCOMISSAO
				,P.DESEMAIL
				,P.DESEMPRESA
				,P.NUMLIMITE
				,P.NUMENDERECO
				,P.NUMSALARIO
				,E.DESRUA
				,E.CODCEP
				,B.DESBAIRRO
				,C.DESCIDADE
				,EST.DESESTADO
				,SP.DESSITUACAO
				,SC.DESSEGMENTOCOMERCIAL  
FROM INFM_PESSOA AS P
INNER JOIN INFM_TIPOPESSOA_PESSOA AS TPP ON TPP.IDPESSOA = P.IDPESSOA
INNER JOIN INFM_TIPOPESSOA AS TP ON TP.IDTIPOPESSOA = TPP.IDTIPOPESSOA
INNER JOIN INFM_FILIALPESSOA AS FP ON FP.IDPESSOA = P.IDPESSOA
INNER JOIN INFM_FILIAL AS F ON F.IDFILIAL = FP.IDFILIAL
LEFT JOIN INFM_ENDERECO AS E ON E.IDENDERECO = P.IDENDERECO
LEFT JOIN INFM_BAIRRO AS B ON B.IDBAIRRO = E.IDBAIRRO
LEFT JOIN INFM_CIDADE AS C ON C.IDCIDADE = B.IDCIDADE
LEFT JOIN INFM_ESTADO AS EST ON EST.IDESTADO = C.IDESTADO
LEFT JOIN INFM_SITUACAO_PESSOA AS SP ON SP.IDSITUACAOPESSOA = P.IDSITUACAOPESSOA
LEFT JOIN INFM_SEGMENTOCOMERCIAL AS SC ON SC.IDSEGMENTOCOMERCIAL = P.IDSEGMENTOCOMERCIAL
WHERE F.IDEMPRESA = @IDEMPRESA AND TP.IDTIPOPESSOA = @IDTIPOPESSOA

