QUERYVALIDACAO select 1 FROM INFM_TIPOPESSOA WHERE CODTIPOPESSOA = 2
BANCODEDADOS IGERENCE
INSERT INTO INFM_TIPOPESSOA
           (IDTIPOPESSOA
           ,DESTIPOPESSOA
           ,CODTIPOPESSOA)
     VALUES
           (2
           ,'Cliente'
           ,2)