QUERYVALIDACAO select 1 FROM INFM_FILIAL WHERE DESFILIAL = 'MATRIZ' AND IDEMPRESA = '1'
BANCODEDADOS IGERENCE
INSERT INTO INFM_FILIAL
           (IDFILIAL
           ,IDEMPRESA
           ,IDENDERECO
           ,IDPESSOA
           ,DESFILIAL
           ,BOLMATRIZ
           ,NUMENDERECO
           ,DESCOMPENDERECO
           ,DESPONTREFENDERECO
           ,DTHABERTURA
           ,DESTELEFONEFIXO
           ,DESTELEFONEFAX
           ,DESTELEFONECEL
           ,OBSFILIAL
           ,DESEMAIL
           ,NUMPISPER
           ,NUMCONFINSPER
           ,NUMOUTDESPPER
           ,NUMCONTSOCPER
           ,CODTABMERCADORIA
		   ,BOLATIVA)
     VALUES
           (1
           ,1
           ,NULL
           ,NULL
           ,'MATRIZ'
           ,1
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
		   ,1)