QUERYVALIDACAO select 1 FROM INFM_FILIALPESSOA WHERE IDFILIAL = '1' AND IDPESSOA = '1'
BANCODEDADOS IGERENCE
INSERT INTO INFM_FILIALPESSOA
           (IDFILIALPESSOA
           ,IDFILIAL
           ,IDPESSOA)
     VALUES
           ('1'
           ,'1'
           ,'1')