QUERYVALIDACAO select 1 FROM INFM_PERMISSAOACAO WHERE IDPERMISSAO = '9' AND IDACAO = '2'
BANCODEDADOS IGERENCE
INSERT INTO INFM_PERMISSAOACAO
          (IDPERMISSAOACAO
           ,IDPERMISSAO
           ,IDACAO)
     VALUES
           ('25'
           ,'9'
           ,'2')