QUERYVALIDACAO select 1 FROM INFM_PERMISSAOACAO WHERE IDPERMISSAO = '12' AND IDACAO = '4'
BANCODEDADOS IGERENCE
INSERT INTO INFM_PERMISSAOACAO
          (IDPERMISSAOACAO
           ,IDPERMISSAO
           ,IDACAO)
     VALUES
           ('35'
           ,'12'
           ,'4')