QUERYVALIDACAO select 1 FROM INFM_PERMISSAOACAO WHERE IDPERMISSAO = '15' AND IDACAO = '2'
BANCODEDADOS IGERENCE
INSERT INTO INFM_PERMISSAOACAO
          (IDPERMISSAOACAO
           ,IDPERMISSAO
           ,IDACAO)
     VALUES
           ('44'
           ,'15'
           ,'2')