QUERYVALIDACAO select 1 FROM INFM_USUPERMISSAOACAO WHERE IDPERMISSAO = '1' AND IDACAO = '3' AND IDPESSOA = '1'
BANCODEDADOS IGERENCE
INSERT INTO INFM_USUPERMISSAOACAO
           (IDUSUPERMISSAOACAO
           ,IDPERMISSAO
           ,IDACAO
           ,IDPESSOA
           ,IDGRUPOPERMISSAO)
     VALUES
           ('1'
           ,'1'
           ,'3'
           ,'1'
		   ,NULL)