QUERYVALIDACAO select 1 FROM INFM_USUPERMISSAOACAO WHERE IDPERMISSAO = '6' AND IDACAO = '2' AND IDPESSOA = '1'
BANCODEDADOS IGERENCE
INSERT INTO INFM_USUPERMISSAOACAO
           (IDUSUPERMISSAOACAO
           ,IDPERMISSAO
           ,IDACAO
           ,IDPESSOA
           ,IDGRUPOPERMISSAO)
     VALUES
           ('2'
           ,'6'
           ,'2'
           ,'1'
		   ,NULL)