QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'AL'
BANCODEDADOS IGERENCE
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('3',
             'AL',
             'ALAGOAS')