QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'AP'
BANCODEDADOS IGERENCE
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('4',
             'AP',
             'AMAPA')