QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'AM'
BANCODEDADOS IGERENCE
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('5',
             'AM',
             'AMAZONAS')