QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'BA'
BANCODEDADOS IGERENCE
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('6',
             'BA',
             'BAHIA')