QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'ES'
BANCODEDADOS IGERENCE
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('9',
             'ES',
             'ESPIRITO SANTO')