QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'MA'
BANCODEDADOS IGERENCE
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('11',
             'MA',
             'MARANHÃO')