QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'MS'
BANCODEDADOS IGERENCE
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('13',
             'MS',
             'MATO GROSSO DO SUL')