QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'PE'
BANCODEDADOS IGERENCE
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('18',
             'PE',
             'PERNAMBUCO')