QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'RJ'
BANCODEDADOS IGERENCE
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('20',
             'RJ',
             'RIO DE JANEIRO')