QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'RS'
BANCODEDADOS IGERENCE
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('22',
             'RS',
             'RIO GRANDE DO SUL')