QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'RR'
BANCODEDADOS IGERENCE
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('24',
             'RR',
             'RORAIMA')