QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'SC'
BANCODEDADOS IGERENCE
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('25',
             'SC',
             'SANTA CATARINA')