QUERYVALIDACAO select 1 FROM INFM_ESTADO WHERE CODESTADO = 'SE'
BANCODEDADOS IGERENCE
INSERT INTO INFM_ESTADO
			(IDESTADO,
             CODESTADO,
             DESESTADO)
VALUES
            ('26',
             'SE',
             'SERGIPE')