QUERYVALIDACAO select 1 FROM INFM_TIPOPRODUTO WHERE CODTIPOPRODUTO = 'SERVICO'
BANCODEDADOS IGERENCE
INSERT INTO INFM_TIPOPRODUTO
			(IDTIPOPRODUTO,
			 CODTIPOPRODUTO,
			 DESTIPOPRODUTO)
VALUES
			('1',
			 'SERVICO',
			 'SERVICO')