QUERYVALIDACAO select 1 FROM INFM_TIPOPRODUTO WHERE CODTIPOPRODUTO = 'PRODUTO'
BANCODEDADOS IGERENCE
INSERT INTO INFM_TIPOPRODUTO
			(IDTIPOPRODUTO,
			 CODTIPOPRODUTO,
			 DESTIPOPRODUTO)
VALUES
			('2',
			 'PRODUTO',
			 'PRODUTO')