QUERYVALIDACAO select 1 FROM INFM_SITUACAO_PESSOA WHERE CODSITUACAO = 'B'
BANCODEDADOS IGERENCE
INSERT INTO INFM_SITUACAO_PESSOA
            (IDSITUACAOPESSOA,
			 DESSITUACAO,
			 CODSITUACAO)
	  VALUES
	        ('6',
			 'SPC Bloqueado',
			 'B')