QUERYVALIDACAO select 1 from sys.sysreferences r join sys.sysobjects o on (o.id = r.constid and o.type = 'F') where r.fkeyid = object_id('INFM_SEGMENTOCOMERCIAL') and o.name = 'FK_INFM_SEG_REFERENCE_INFM_EMP'
BANCODEDADOS IGERENCE
ALTER TABLE INFM_SEGMENTOCOMERCIAL
   ADD CONSTRAINT FK_INFM_SEG_REFERENCE_INFM_EMP FOREIGN KEY (IDEMPRESA)
      REFERENCES INFM_EMPRESA (IDEMPRESA)