QUERYVALIDACAO select 1 FROM INFM_TIPODOCUMENTO WHERE CODTIPODOCUMENTO = 'A'
BANCODEDADOS IGERENCE
INSERT INTO INFM_TIPODOCUMENTO
           (IDTIPODOCUMENTO
           ,CODTIPODOCUMENTO
           ,DESTIPODOCUMENTO)
     VALUES
           ('1'
           ,'A'
           ,'Avulso')