QUERYVALIDACAO select 1 FROM INFM_TIPODOCUMENTO WHERE CODTIPODOCUMENTO = 'C'
BANCODEDADOS IGERENCE
INSERT INTO INFM_TIPODOCUMENTO
           (IDTIPODOCUMENTO
           ,CODTIPODOCUMENTO
           ,DESTIPODOCUMENTO)
     VALUES
           ('4'
           ,'C'
           ,'Credito')