QUERYVALIDACAO select 1 FROM INFM_LOCALDOCUMENTO WHERE CODLOCALDOCUMENTO = 'P'
BANCODEDADOS IGERENCE
INSERT INTO INFM_LOCALDOCUMENTO
           (IDLOCALDOCUMENTO
           ,CODLOCALDOCUMENTO
           ,DESLOCALDOCUMENTO)
     VALUES
           ('3'
           ,'P'
           ,'Protestado')