QUERYVALIDACAO select 1 FROM INFM_PUBLICIDADE WHERE CODPUBLICIDADE = '1'
BANCODEDADOS IGERENCE
INSERT INTO INFM_PUBLICIDADE
           (IDPUBLICIDADE
           ,CODPUBLICIDADE
           ,DESPUBLICIDADE)
     VALUES
           ('1'
           ,'1'
           ,'Indicação de Amigo')