QUERYVALIDACAO select 1 FROM INFM_PERMISSAOACAO WHERE IDPERMISSAO = '24' AND IDACAO = '2'
BANCODEDADOS IGERENCE
INSERT INTO INFM_PERMISSAOACAO
          (IDPERMISSAOACAO
           ,IDPERMISSAO
           ,IDACAO)
     VALUES
           ('70'
           ,'24'
           ,'2')