QUERYVALIDACAO SELECT 1 FROM SYS.TABLES AS T JOIN SYS.COLUMNS AS C ON T.OBJECT_ID = C.OBJECT_ID WHERE T.TYPE = 'U' AND T.NAME = 'INFM_CRM' AND C.NAME = 'BOLATIVO'
BANCODEDADOS IGERENCE
ALTER TABLE INFM_CRM ADD BOLATIVO LOGICO not null