QUERYVALIDACAO SELECT 1 FROM SYS.TABLES AS T JOIN SYS.COLUMNS AS C ON T.OBJECT_ID = C.OBJECT_ID WHERE T.TYPE = 'U' AND T.NAME = 'INFM_RESPOSTAPERGUNTA' AND C.NAME = 'IDPESSOACRM'
BANCODEDADOS IGERENCE
ALTER TABLE INFM_RESPOSTAPERGUNTA ADD IDPESSOACRM OBJETO_ID not null