QUERYVALIDACAO select 1 from sys.sysobjects o  where o.name = 'SP_RECUPERAR_AGENDAMENTO'
BANCODEDADOS IGERENCE
CREATE PROCEDURE SP_RECUPERAR_AGENDAMENTO @IDPESSOACADASTRO VARCHAR(36),
										  @IDPESSOACLIENTE VARCHAR(36),
										  @DESCRM VARCHAR(200),
										  @DTHPROXAGENDAMENTOINI DATETIME,
										  @DTHPROXAGENDAMENTOFIM DATETIME,
										  @VALIDACOESTOTAIS BIT,
										  @BOLATIVO VARCHAR(2),
										  @IDPESSOA VARCHAR(MAX),
										  @IDEMPRESA VARCHAR(36)
AS

DECLARE @SQL AS VARCHAR(8000)
DECLARE @WHERE AS VARCHAR(8000)
DECLARE @DATAINICIO DATETIME
DECLARE @DATAFIM DATETIME

if (object_id('tempdb..#CRM') is not null) drop table #CRM

if (object_id('tempdb..#GRUPOCRM') is not null) drop table #GRUPOCRM

CREATE TABLE #GRUPOCRM (CODGRUPOCOMPROMISSO VARCHAR(50),
						DESGRUPOCOMPROMISSO VARCHAR(200),
						IDGRUPOCOMPROMISSO  VARCHAR(36),
						IDGRUPOCOMPROMISSO_PAI VARCHAR(36),
						NELNIVEL INTEGER);

CREATE TABLE #CRM (
      IDCRM					VARCHAR(36),
      IDPESSOACADASTRO		VARCHAR(36),
      IDPESSOACLIENTE		VARCHAR(36),
      CODCRM				VARCHAR(50),
	  OBSCOMPROMISSO		VARCHAR(MAX),
	  DESCRM				VARCHAR(200),
	  BOLATIVO				BIT,
	  DTHPROXAGENDAMENTO	DATETIME,
	  DTHPROXAGENDAMENTOFIN DATETIME,
	  IDPESSOACRM			VARCHAR(36),
	  IDGRUPOCOMPROMISSO	VARCHAR(36),
	  DESAGENDAMENTO		VARCHAR(200),
	  DESNOME				VARCHAR(200));
	  
SET @SQL = ' INSERT INTO #CRM
      SELECT DISTINCT C.IDCRM
      ,C.IDPESSOACADASTRO
      ,C.IDPESSOACLIENTE
      ,C.CODCRM
      ,C.OBSCOMPROMISSO
      ,C.DESCRM
      ,C.BOLATIVO
	  ,PC.DTHPROXAGENDAMENTO
	  ,PC.DTHPROXAGENDAMENTOFIN
	  ,PC.IDPESSOACRM
	  ,PC.IDGRUPOCOMPROMISSO
	  ,PC.DESAGENDAMENTO
	  ,P.DESNOME
FROM INFM_CRM C
INNER JOIN INFM_PESSOACRM PC ON PC.IDCRM = C.IDCRM
INNER JOIN INFM_PESSOACRM PC1 ON PC1.IDCRM = C.IDCRM
INNER JOIN INFM_PESSOACRMPESSOA PCP ON PCP.IDPESSOACRM = PC.IDPESSOACRM
INNER JOIN INFM_PESSOA P ON P.IDPESSOA = PCP.IDPESSOA '

INSERT INTO INFM_DEBUG VALUES(@DTHPROXAGENDAMENTOINI)

SET @WHERE = ' WHERE C.IDEMPRESA = ' + '''' + @IDEMPRESA + ''''

IF (NOT @IDPESSOACADASTRO IS NULL AND @IDPESSOACADASTRO <> '')
BEGIN
SET @WHERE = @WHERE + ' AND C.IDPESSOACADASTRO = ' + '''' + @IDPESSOACADASTRO + ''''
END 

IF (NOT @IDPESSOACLIENTE IS NULL AND @IDPESSOACLIENTE <> '')
BEGIN
SET @WHERE = @WHERE + ' AND C.IDPESSOACLIENTE = ' + '''' + @IDPESSOACLIENTE + ''''
END

IF (NOT @DESCRM IS NULL AND @DESCRM <> '')
BEGIN
SET @WHERE = @WHERE + ' AND C.DESCRM LIKE ' + '''' +  @DESCRM + ''''
END

IF (NOT @BOLATIVO IS NULL AND @BOLATIVO <> '')
BEGIN
SET @WHERE = @WHERE + ' AND C.BOLATIVO = ' + '''' + @BOLATIVO + ''''
END

IF (NOT @DTHPROXAGENDAMENTOINI IS NULL)
BEGIN

SET @WHERE = @WHERE + ' AND PC1.DTHPROXAGENDAMENTO >= ' + '''' + FORMAT(@DTHPROXAGENDAMENTOINI, 'MM/dd/yyyy', 'en-us') + ' ' + Right(IsNull(Convert(Varchar,@DTHPROXAGENDAMENTOINI,100),''),7) + '''' 
END

IF (NOT @DTHPROXAGENDAMENTOFIM IS NULL)
BEGIN
SET @WHERE = @WHERE + ' AND PC1.DTHPROXAGENDAMENTOFIN <= ' + '''' + FORMAT(@DTHPROXAGENDAMENTOFIM, 'MM/dd/yyyy', 'en-us') + ' ' + Right(IsNull(Convert(Varchar,@DTHPROXAGENDAMENTOFIM,100),''),7) + '''' 
END

IF (NOT @IDPESSOA IS NULL AND @IDPESSOA <> '')
BEGIN
SET @WHERE = @WHERE + ' AND PCP.IDPESSOA IN (' + '''' +REPLACE(@IDPESSOA, ',', '''' + ',' + '''') + '''' + ')'
END

SET @WHERE = @WHERE + ' ORDER BY PC.DTHPROXAGENDAMENTO '

EXEC (@SQL + @WHERE)


SELECT *
FROM #CRM

SELECT DISTINCT P.IDPESSOA,
				P.CODPESSOA,
				P.DESNOME,
				P.BOLCONSULTOR,
				P.CODLOGIN,
				P.DESTELEFONEFIXO,
				P.DESTELEFONECELULAR
FROM INFM_PESSOA P
INNER JOIN #CRM C ON C.IDPESSOACLIENTE = P.IDPESSOA 

SELECT DISTINCT P.IDPESSOA,
				P.CODPESSOA,
				P.DESNOME,
				P.BOLCONSULTOR,
				P.CODLOGIN,
				P.DESTELEFONEFIXO,
				P.DESTELEFONECELULAR
FROM INFM_PESSOA P
INNER JOIN #CRM C ON C.IDPESSOACADASTRO = P.IDPESSOA 

INSERT INTO #GRUPOCRM
SELECT DISTINCT GP.CODGRUPOCOMPROMISSO,
                GP.DESGRUPOCOMPROMISSO,
				GP.IDGRUPOCOMPROMISSO,
				NULL IDGRUPOCOMPROMISSO_PAI,
				1 NELNIVEL
FROM INFM_GRUPOCOMPROMISSO GP
INNER JOIN #CRM C ON C.IDGRUPOCOMPROMISSO = GP.IDGRUPOCOMPROMISSO

EXEC SP_RECUPERAR_GRUPOCOMPROMISSO 1

SELECT DISTINCT GP.CODGRUPOCOMPROMISSO,
                GP.DESGRUPOCOMPROMISSO,
				GP.IDGRUPOCOMPROMISSO
FROM #GRUPOCRM GP

SELECT DISTINCT RP.IDPESSOACRM,
                P.IDPERGUNTA,
				P.DESPERGUNTA,
				P.BOLOBRIGATORIA,
				P.CODTIPOCOMPONENTE,
				P.BOLNUMERICO,
				RP.DESVALOR
FROM INFM_PERGUNTAS P
INNER JOIN INFM_RESPOSTAPERGUNTA RP ON RP.IDPERGUNTA = P.IDPERGUNTA
INNER JOIN #CRM C ON C.IDPESSOACRM = RP.IDPESSOACRM

SELECT DISTINCT P.IDPESSOA,
				P.CODPESSOA,
				P.DESNOME,
				P.BOLCONSULTOR,
				P.CODLOGIN,
				P.DESTELEFONEFIXO,
				P.DESTELEFONECELULAR,
				PC.IDPESSOACRM
FROM INFM_PESSOA P
INNER JOIN INFM_PESSOACRMPESSOA PCP ON PCP.IDPESSOA = P.IDPESSOA
INNER JOIN INFM_PESSOACRM PC ON PC.IDPESSOACRM = PCP.IDPESSOACRM
INNER JOIN #CRM C ON C.IDPESSOACRM = PCP.IDPESSOACRM AND C.IDCRM = PC.IDCRM