QUERYVALIDACAO select 1 from sys.sysobjects o  where o.name = 'SP_RECUPERAR_AGENDAMENTO_DET'
BANCODEDADOS IGERENCE
CREATE PROCEDURE SP_RECUPERAR_AGENDAMENTO_DET @IDCRM VARCHAR(36)
AS

if (object_id('tempdb..#CRM_DET') is not null) drop table #CRM_DET

if (object_id('tempdb..#GRUPOCRM') is not null) drop table #GRUPOCRM

if (object_id('tempdb..#PROPOSTA') is not null) drop table #PROPOSTA

CREATE TABLE #GRUPOCRM (CODGRUPOCOMPROMISSO VARCHAR(50),
						DESGRUPOCOMPROMISSO VARCHAR(200),
						IDGRUPOCOMPROMISSO  VARCHAR(36),
						IDGRUPOCOMPROMISSO_PAI  VARCHAR(36),
						NELNIVEL INTEGER);

CREATE TABLE #CRM_DET (
      IDCRM					VARCHAR(36),
      IDPESSOACADASTRO		VARCHAR(36),
      IDPESSOACLIENTE		VARCHAR(36),
      CODCRM				VARCHAR(50),
	  OBSCOMPROMISSO		VARCHAR(MAX),
	  DESCRM				VARCHAR(200),
	  IDEMPRESA				VARCHAR(36),
	  BOLATIVO				BIT,
	  BOLCONCLUIDO          BIT,
	  DTHPROXAGENDAMENTO	DATETIME,
	  DTHPROXAGENDAMENTOFIN DATETIME,
	  IDPESSOACRM			VARCHAR(36),
	  IDGRUPOCOMPROMISSO	VARCHAR(36),
	  DESAGENDAMENTO		VARCHAR(200),
	  IDSTATUSCRM			VARCHAR(36),
	  CODSTATUSCRM			VARCHAR(50),
	  DESSTATUSCRM          VARCHAR(200),
	  IDTIPOCRM             VARCHAR(36),
	  DESTIPOCRM            VARCHAR(100));

CREATE TABLE #PROPOSTA (
      IDPROPOSTA	 VARCHAR(36),
      IDCRM VARCHAR(36),
      DESPROPOSTA VARCHAR(200),
      NUMPROPOSTAVENDA DECIMAL,
      NUMPROPOSTAMANUTENCAO DECIMAL,
      NUMCONTRAPROPOSTAVENDA DECIMAL,
      NUMCONTRAPROPOSTAMANUT DECIMAL,
      DESOPNIAO VARCHAR(200),
      DESDUVIDA VARCHAR(200),
      BOLATENDENECESSIDADE BIT,
      DTINSTALACAO DATETIME,
      BOLATIVA BIT,
      CODPROPOSTA VARCHAR(50),
	  IDPESSOA VARCHAR(36),
	  IDPESSOACLIENTE  VARCHAR(36));

INSERT INTO #CRM_DET
      SELECT C.IDCRM
      ,C.IDPESSOACADASTRO
      ,C.IDPESSOACLIENTE
      ,C.CODCRM
      ,C.OBSCOMPROMISSO
      ,C.DESCRM
	  ,C.IDEMPRESA
      ,C.BOLATIVO
	  ,PC.BOLCONCLUIDO
	  ,PC.DTHPROXAGENDAMENTO
	  ,PC.DTHPROXAGENDAMENTOFIN
	  ,PC.IDPESSOACRM
	  ,PC.IDGRUPOCOMPROMISSO
	  ,PC.DESAGENDAMENTO
	  ,SCRM.IDSTATUSCRM
	  ,SCRM.CODSTATUSCRM
	  ,SCRM.DESSTATUSCRM
	  ,TCRM.IDTIPOCRM
	  ,TCRM.DESTIPOCRM
FROM INFM_CRM C
INNER JOIN INFM_PESSOACRM PC ON PC.IDCRM = C.IDCRM 
INNER JOIN INFM_STATUS_CRM SCRM ON SCRM.IDSTATUSCRM = C.IDSTATUSCRM
INNER JOIN INFM_TIPOCRM TCRM ON TCRM.IDTIPOCRM	= C.IDTIPOCRM
WHERE C.IDCRM =  @IDCRM 
ORDER BY PC.DESAGENDAMENTO 

SELECT *
FROM #CRM_DET

INSERT INTO #PROPOSTA
SELECT IDPROPOSTA
      ,IDCRM
      ,DESPROPOSTA
      ,NUMPROPOSTAVENDA
      ,NUMPROPOSTAMANUTENCAO
      ,NUMCONTRAPROPOSTAVENDA
      ,NUMCONTRAPROPOSTAMANUT
      ,DESOPNIAO
      ,DESDUVIDA
      ,BOLATENDENECESSIDADE
      ,DTINSTALACAO
      ,BOLATIVA
      ,CODPROPOSTA
	  ,IDPESSOA
	  ,IDPESSOACLIENTE
  FROM INFM_PROPOSTA
  WHERE IDCRM = @IDCRM

SELECT *
FROM #PROPOSTA

SELECT DISTINCT P.IDPESSOA,
				P.CODPESSOA,
				P.DESNOME,
				P.BOLCONSULTOR,
				P.CODLOGIN,
				P.DESTELEFONEFIXO,
				P.DESTELEFONECELULAR
FROM INFM_PESSOA P
INNER JOIN #PROPOSTA PR ON PR.IDPESSOACLIENTE = P.IDPESSOA 

SELECT DISTINCT P.IDPESSOA,
				P.CODPESSOA,
				P.DESNOME,
				P.BOLCONSULTOR,
				P.CODLOGIN,
				P.DESTELEFONEFIXO,
				P.DESTELEFONECELULAR
FROM INFM_PESSOA P
INNER JOIN #CRM_DET C ON C.IDPESSOACLIENTE = P.IDPESSOA 

SELECT DISTINCT P.IDPESSOA,
				P.CODPESSOA,
				P.DESNOME,
				P.BOLCONSULTOR,
				P.CODLOGIN,
				P.DESTELEFONEFIXO,
				P.DESTELEFONECELULAR
FROM INFM_PESSOA P
INNER JOIN #CRM_DET C ON C.IDPESSOACADASTRO = P.IDPESSOA 

INSERT INTO #GRUPOCRM
SELECT DISTINCT GP.CODGRUPOCOMPROMISSO,
                GP.DESGRUPOCOMPROMISSO,
				GP.IDGRUPOCOMPROMISSO,
				NULL IDGRUPOCOMPROMISSO_PAI,
				1 NELNIVEL
FROM INFM_GRUPOCOMPROMISSO GP
INNER JOIN #CRM_DET C ON C.IDGRUPOCOMPROMISSO = GP.IDGRUPOCOMPROMISSO

EXEC SP_RECUPERAR_GRUPOCOMPROMISSO 1

SELECT DISTINCT GP.CODGRUPOCOMPROMISSO,
                GP.DESGRUPOCOMPROMISSO,
				GP.IDGRUPOCOMPROMISSO
FROM #GRUPOCRM GP

SELECT DISTINCT RP.IDPESSOACRM,
                P.IDPERGUNTA,
				P.DESPERGUNTA,
				P.BOLOBRIGATORIA,
				P.CODTIPOCOMPONENTE,
				P.BOLNUMERICO,
				RP.DESVALOR
FROM INFM_PERGUNTAS P
INNER JOIN INFM_RESPOSTAPERGUNTA RP ON RP.IDPERGUNTA = P.IDPERGUNTA
INNER JOIN #CRM_DET C ON C.IDPESSOACRM = RP.IDPESSOACRM

SELECT DISTINCT P.IDPESSOA,
				P.CODPESSOA,
				P.DESNOME,
				P.BOLCONSULTOR,
				P.CODLOGIN,
				P.DESTELEFONEFIXO,
				P.DESTELEFONECELULAR,
				PC.IDPESSOACRM
FROM INFM_PESSOA P
INNER JOIN INFM_PESSOACRMPESSOA PCP ON PCP.IDPESSOA = P.IDPESSOA
INNER JOIN INFM_PESSOACRM PC ON PC.IDPESSOACRM = PCP.IDPESSOACRM
INNER JOIN #CRM_DET C ON C.IDPESSOACRM = PCP.IDPESSOACRM AND C.IDCRM = PC.IDCRM