QUERYVALIDACAO select 1 from sys.sysobjects o  where o.name = 'SP_PESQUISAR_GRUPO_COMPROMISSO'
BANCODEDADOS IGERENCE
CREATE PROCEDURE SP_PESQUISAR_GRUPO_COMPROMISSO @DESGRUPOCOMPROMISSO VARCHAR(200),
                                                        @IDGRUPOCOMPROMISSO VARCHAR(36),
                                                        @IDEMPRESA VARCHAR(36),
														@ORDENAR BIT,
														@RECUPERARSUBGRUPO BIT,
														@RECUPERARPERGUNTAS BIT
AS

DECLARE @SQL AS VARCHAR(8000)

if (object_id('tempdb..#GRUPOCRM') is not null) drop table #GRUPOCRM

if (object_id('tempdb..#PERGUNTAS') is not null) drop table #PERGUNTAS

CREATE TABLE #GRUPOCRM (CODGRUPOCOMPROMISSO VARCHAR(50),
						DESGRUPOCOMPROMISSO VARCHAR(200),
						IDGRUPOCOMPROMISSO  VARCHAR(36),
						IDGRUPOCOMPROMISSO_PAI  VARCHAR(36),
						NELNIVEL INTEGER);

CREATE TABLE #PERGUNTAS (IDPERGUNTA  VARCHAR(36),
						 DESPERGUNTA VARCHAR(200),
                         BOLOBRIGATORIA BIT,
                         CODTIPOCOMPONENTE VARCHAR(20),
                         BOLNUMERICO BIT,
						 IDGRUPOCOMPROMISSO VARCHAR(36));

SET @SQL = 'INSERT INTO #GRUPOCRM
			SELECT DISTINCT GP.CODGRUPOCOMPROMISSO,
							GP.DESGRUPOCOMPROMISSO,
							GP.IDGRUPOCOMPROMISSO,
							NULL IDGRUPOCOMPROMISSO_PAI,
							1 NELNIVEL
			FROM INFM_GRUPOCOMPROMISSO GP 
			WHERE NOT EXISTS (SELECT IDGRUPOCOMPROMISSO 
										     FROM INFM_GRUPOCOMPROMISSOSUBGRUPO
										     WHERE IDGRUPOCOMPROMISSO = GP.IDGRUPOCOMPROMISSO) '

SET @SQL = @SQL + ' AND GP.IDEMPRESA =  ' + '''' + @IDEMPRESA + ''''

IF (NOT @DESGRUPOCOMPROMISSO IS NULL AND @DESGRUPOCOMPROMISSO <> '')
BEGIN
SET @SQL = @SQL + ' AND GP.DESGRUPOCOMPROMISSO LIKE  ' + '''' + @DESGRUPOCOMPROMISSO + ''''
END 

IF (NOT @IDGRUPOCOMPROMISSO IS NULL AND @IDGRUPOCOMPROMISSO <> '')
BEGIN
SET @SQL = @SQL + ' AND GP.IDGRUPOCOMPROMISSO =  ' + '''' + @IDGRUPOCOMPROMISSO + ''''
END 

IF (NOT @ORDENAR IS NULL AND @ORDENAR = 1)
BEGIN
SET @SQL = @SQL + ' ORDER BY GP.DESGRUPOCOMPROMISSO '
END 

EXEC (@SQL)

IF (NOT @RECUPERARSUBGRUPO IS NULL AND @RECUPERARSUBGRUPO = 1)
BEGIN
EXEC SP_RECUPERAR_GRUPOCOMPROMISSO 1
END

SELECT DISTINCT GP.CODGRUPOCOMPROMISSO,
                GP.DESGRUPOCOMPROMISSO,
				GP.IDGRUPOCOMPROMISSO,
				IDGRUPOCOMPROMISSO_PAI
FROM #GRUPOCRM GP

IF (NOT @RECUPERARPERGUNTAS IS NULL AND @RECUPERARPERGUNTAS = 1)
BEGIN

INSERT INTO #PERGUNTAS
SELECT P.IDPERGUNTA
      ,P.DESPERGUNTA
      ,P.BOLOBRIGATORIA
      ,P.CODTIPOCOMPONENTE
      ,P.BOLNUMERICO
	  ,P.IDGRUPOCOMPROMISSO
FROM INFM_PERGUNTAS P
INNER JOIN #GRUPOCRM GP ON GP.IDGRUPOCOMPROMISSO = P.IDGRUPOCOMPROMISSO
ORDER BY P.DESPERGUNTA

SELECT *
FROM #PERGUNTAS

SELECT PO.IDPERGUNTAOPCAO
      ,PO.DESPERGUNTAOPCAO
	  ,P.IDPERGUNTA
FROM INFM_PERGUNTAOPCAO PO
INNER JOIN #PERGUNTAS P ON  P.IDPERGUNTA = PO.IDPERGUNTA

END