QUERYVALIDACAO select 1 FROM INFM_PARAMETROS WHERE CODPARAMETRO = 'SERVIDORBD'
BANCODEDADOS IGERENCE
INSERT INTO INFM_PARAMETROS
          (IDPARAMETRO
           ,CODPARAMETRO
           ,DESPARAMETRO
		   ,TIPOCOMPONENTE
		   ,BOLNIVELFILIAL)
     VALUES
           (NEWID()
           ,'SERVIDORBD'
           ,'Servidor Base de Dados'
		   ,1
		   ,1)