QUERYVALIDACAO select 1 FROM INFM_PARAMETROS WHERE CODPARAMETRO = 'NOMEBD'
BANCODEDADOS IGERENCE
INSERT INTO INFM_PARAMETROS
          (IDPARAMETRO
           ,CODPARAMETRO
           ,DESPARAMETRO
		   ,TIPOCOMPONENTE
		   ,BOLNIVELFILIAL)
     VALUES
           (NEWID()
           ,'NOMEBD'
           ,'Nome Base de Dados'
		   ,1
		   ,1)