QUERYVALIDACAO select 1 FROM INFM_PARAMETROS WHERE CODPARAMETRO = 'USUARIOBD'
BANCODEDADOS IGERENCE
INSERT INTO INFM_PARAMETROS
          (IDPARAMETRO
           ,CODPARAMETRO
           ,DESPARAMETRO
		   ,TIPOCOMPONENTE
		   ,BOLNIVELFILIAL)
     VALUES
           (NEWID()
           ,'USUARIOBD'
           ,'Usuario Base de Dados'
		   ,1
		   ,1)