QUERYVALIDACAO select 1 FROM INFM_PARAMETROS WHERE CODPARAMETRO = 'AUTENTICACAOINTEGRADA'
BANCODEDADOS IGERENCE
INSERT INTO INFM_PARAMETROS
          (IDPARAMETRO
           ,CODPARAMETRO
           ,DESPARAMETRO
		   ,TIPOCOMPONENTE
		   ,BOLNIVELFILIAL)
     VALUES
           (NEWID()
           ,'AUTENTICACAOINTEGRADA'
           ,'Autenticação Integrada'
		   ,3
		   ,1)