QUERYVALIDACAO select 1 from  sysindexes where  id    = object_id('INFM_CODIGOBARRASPRODSERV') and   name  = 'AK_INFM_CODIGOBARRASPRODSERV1' and   indid > 0 and   indid < 255
BANCODEDADOS IGERENCE
create unique index AK_INFM_CODIGOBARRASPRODSERV1 on INFM_CODIGOBARRASPRODSERV (
DESCODBARRAS ASC,
IDEMPRESA ASC)