QUERYVALIDACAO SELECT 1 FROM SYS.TABLES AS T JOIN SYS.COLUMNS AS C ON T.OBJECT_ID = C.OBJECT_ID WHERE T.TYPE = 'U' AND T.NAME = 'INFM_PARAMETROVALOR' AND C.NAME = 'IDEMPRESA'
BANCODEDADOS IGERENCE
ALTER TABLE INFM_PARAMETROVALOR ADD IDEMPRESA OBJETO_ID NULL