QUERYVALIDACAO SELECT 1 FROM SYS.TABLES AS T JOIN SYS.COLUMNS AS C ON T.OBJECT_ID = C.OBJECT_ID WHERE T.TYPE = 'U' AND T.NAME = 'INFM_PERMISSAO' AND C.NAME = 'CODPERMISSAO' AND c.max_length = 50
BANCODEDADOS IGERENCE
ALTER TABLE INFM_PERMISSAO ALTER COLUMN CODPERMISSAO DESCRICAO50