QUERYVALIDACAO select 1 FROM INFM_PERMISSAO WHERE CODPERMISSAO = 'REALIZAR_COMPRA_OUTRA_FILIAL'
BANCODEDADOS IGERENCE
INSERT INTO INFM_PERMISSAO
           (IDPERMISSAO
           ,CODPERMISSAO
           ,DESPERMISSAO
		   ,BOLOBRIGATORIA)
     VALUES
           (NEWID()
           ,'REALIZAR_COMPRA_OUTRA_FILIAL'
           ,'Realiza compra para outra filial'
		   ,0)