QUERYVALIDACAO SELECT 1 FROM SYS.TABLES AS T JOIN SYS.COLUMNS AS C ON T.OBJECT_ID = C.OBJECT_ID WHERE T.TYPE = 'U' AND T.NAME = 'INFM_CAIXA' AND C.NAME = 'DESHOST'
BANCODEDADOS IGERENCE
ALTER TABLE INFM_CAIXA ADD DESHOST DESCRICAO100 not null