QUERYVALIDACAO select 1 FROM INFM_GRUPOPARAMETRO WHERE CODGRUPOPARAMETRO = 'OPERATIVO'
BANCODEDADOS IGERENCE
INSERT INTO INFM_GRUPOPARAMETRO
           (IDGRUPOPARAMETRO
           ,CODGRUPOPARAMETRO
           ,DESGRUPOPARAMETRO)
     VALUES
           (NEWID()
           ,'OPERATIVO'
           ,'Operativo')