QUERYVALIDACAO select 1 FROM INFM_GRUPOPARAMETRO WHERE CODGRUPOPARAMETRO = 'SERVER'
BANCODEDADOS IGERENCE
INSERT INTO INFM_GRUPOPARAMETRO
           (IDGRUPOPARAMETRO
           ,CODGRUPOPARAMETRO
           ,DESGRUPOPARAMETRO)
     VALUES
           (NEWID()
           ,'SERVER'
           ,'I - GERENCE Server')