QUERYVALIDACAO select 1 from sys.sysobjects o  where o.name = 'SP_RECUPERAR_PRODUTOS'
BANCODEDADOS IGERENCE
CREATE PROCEDURE [dbo].[SP_RECUPERAR_PRODUTOS]  @IDEMPRESA  VARCHAR(36),
												@IDFILIAL   VARCHAR(36),
												@DTATUAL    DATE,
												@DESPRODUTO VARCHAR(200),
												@CODPRODUTO VARCHAR(50),
												@BOLIMAGEM	BIT

AS

DECLARE @SQL AS VARCHAR(8000)
DECLARE @WHERE AS VARCHAR(8000)
DECLARE @DATAINICIO DATETIME
DECLARE @DATAFIM DATETIME

if (object_id('tempdb..#PRODUTO') is not null) drop table #PRODUTO

if (object_id('tempdb..#PRODUTOFILIAL') is not null) drop table #PRODUTOFILIAL

CREATE TABLE #PRODUTO (IDPRODUTOSERVICO VARCHAR(36),
					   CODPRODUTO int,
					   DESPRODUTO VARCHAR(100),
					   BOLVENDAAGRANEL bit,
					   BOLINTERNO bit,
					   BOLACRESCIMO bit,
					   BOLVENDANUMEROSERIE bit,
					   OBSPRODUTO VARCHAR(500),
					   DESCODBARRAS VARCHAR(50),
					   IDUNIDADEMEDIDA VARCHAR(36),
					   CODUNIDADEMEDIDA VARCHAR(20),
					   NUMUNIDADEPAI decimal(8,2),
					   DESUNIDADEMEDIDA VARCHAR(100),
					   IDTIPOPRODUTO VARCHAR(36),
					   CODTIPOPRODUTO VARCHAR(20),
					   DESTIPOPRODUTO VARCHAR(50),
					   IDGRUPOPRODUTO VARCHAR(36),
					   CODGRUPOPRODUTO int,
					   DESGRUPOPRODUTO VARCHAR(50),					  
					   IDPRODUTOMARCA VARCHAR(36),
					   CODPRODUTOMARCA INT,
					   DESPRODUTOMARCA VARCHAR(50),
					   IDPRODCATEGORIA VARCHAR(36),
					   CODPRODCATEGORIA INT,
					   DESPRODCATEGORIA VARCHAR(50),
					   IDSETOREMPRESA VARCHAR(36),
					   DESSETOR VARCHAR(200),
					   DESIMPRESSORA VARCHAR(500));

SET @SQL = ' INSERT INTO #PRODUTO
				SELECT P.IDPRODUTOSERVICO
	  ,P.CODPRODUTO
	  ,P.DESPRODUTO
	  ,P.BOLVENDAAGRANEL
	  ,P.BOLINTERNO
	  ,P.BOLACRESCIMO
	  ,P.BOLVENDANUMEROSERIE
	  ,P.OBSPRODUTO
	  ,P.DESCODBARRAS
	  ,UM.IDUNIDADEMEDIDA
	  ,UM.CODUNIDADEMEDIDA
	  ,UM.NUMUNIDADEPAI
	  ,UM.DESUNIDADEMEDIDA
	  ,TP.IDTIPOPRODUTO
	  ,TP.CODTIPOPRODUTO
	  ,TP.DESTIPOPRODUTO
	  ,GP.IDGRUPOPRODUTO
	  ,GP.CODGRUPOPRODUTO
	  ,GP.DESGRUPOPRODUTO
	  ,PM.IDPRODUTOMARCA
	  ,PM.CODPRODUTOMARCA
	  ,PM.DESPRODUTOMARCA
	  ,PC.IDPRODCATEGORIA
	  ,PC.CODPRODCATEGORIA
	  ,PC.DESPRODCATEGORIA
	  ,SE.IDSETOREMPRESA
	  ,SE.DESSETOR
	  ,SE.DESIMPRESSORA
FROM INFM_PRODUTOSERVICO P
					INNER JOIN INFM_UNIDADEMEDPRODUTO UMP ON UMP.IDPRODUTOSERVICO = P.IDPRODUTOSERVICO
					INNER JOIN INFM_UNIDADEMEDIDA UM ON UM.IDUNIDADEMEDIDA = UMP.IDUNIDADEMEDIDA
					INNER JOIN INFM_PRODUTOFILIAL PF ON PF.IDPRODUTOSERVICO = P.IDPRODUTOSERVICO
					LEFT JOIN INFM_TIPOPRODUTO TP ON TP.IDTIPOPRODUTO = P.IDTIPOPRODUTO
					LEFT JOIN INFM_GRUPOPRODUTO GP ON GP.IDGRUPOPRODUTO = P.IDGRUPOPRODUTO
					LEFT JOIN INFM_PRODUTOMARCA PM ON PM.IDPRODUTOMARCA = P.IDPRODUTOMARCA
					LEFT JOIN INFM_PRODCATEGORIA PC ON PC.IDPRODCATEGORIA = P.IDPRODCATEGORIA
					LEFT JOIN INFM_SETOREMPRESA SE ON SE.IDSETOREMPRESA = PF.IDSETOREMPRESA'
SET @WHERE = ' WHERE P.IDEMPRESA = ' + '''' + @IDEMPRESA + '''' +  ' AND PF.IDFILIAL = ' + '''' + @IDFILIAL + ''''
EXEC (@SQL + @WHERE)


-- PRODUTOS [0]
SELECT *
FROM #PRODUTO

-- ACRESCIMOS DO PRODUTO [1]
SELECT AP.IDACRESCIMO
      ,AP.IDPRODUTOSERVICO
	  ,P.DESPRODUTO	  
FROM INFM_PRODUTOSERVICO P 
INNER JOIN INFM_ACRESCIMOPRODUTO AP ON AP.IDACRESCIMO = P.IDPRODUTOSERVICO
INNER JOIN #PRODUTO PP ON PP.IDPRODUTOSERVICO = AP.IDPRODUTOSERVICO
WHERE P.BOLACRESCIMO = 1

-- OBSERVACOES DO PRODUTO [2]
SELECT OBS.IDOBSERVACAO
	  ,OBS.DESOBSERVACAO
	  ,P.IDPRODUTOSERVICO
FROM INFM_OBSERVACAOPRODUTO OBSP INNER JOIN #PRODUTO P ON P.IDPRODUTOSERVICO = OBSP.IDPRODUTOSERVICO
								 INNER JOIN INFM_OBSERVACAO OBS ON OBS.IDOBSERVACAO = OBSP.IDOBSERVACAO

-- CODIGO BARRAS PRODUTO [3]
SELECT CB.IDPRODUTOSERVICO
	   ,CB.IDCODIGOBARRASPRODSERV
	   ,CB.DESCODBARRAS
FROM INFM_CODIGOBARRASPRODSERV CB INNER JOIN #PRODUTO P ON P.IDPRODUTOSERVICO = CB.IDPRODUTOSERVICO

-- UNIDADES DE MEDIDA [4]
SELECT *
FROM INFM_UNIDADEMEDIDA

-- PRODUTOS FILIAL [5]
SELECT PF.* FROM 
INFM_PRODUTOFILIAL PF INNER JOIN #PRODUTO P ON P.IDPRODUTOSERVICO = PF.IDPRODUTOSERVICO
WHERE PF.IDFILIAL = @IDFILIAL

-- PROMOCAO PRODUTOS [6]
select P.IDPRODUTOSERVICO,
	   pp.numpromocaoper, 
	   pp.numpromocaovalor,
	   PP.DTHINICIO,
	   PP.DTHFIM, 
	   dp.coddiasemana
from #PRODUTO P INNER JOIN infm_produtopromocaoprodf pf 
					ON PF.IDPRODUTOSERVICO = P.IDPRODUTOSERVICO
			    INNER JOIN infm_produtopromocao pp
					ON PP.IDPRODUTOPROMOCAO = PF.IDPRODUTOPROMOCAO 
				left join infm_diasemanapromocao dp 
					on dp.idprodutopromocao = pp.idprodutopromocao


-- RECUPERAR IMAGENS
IF (@BOLIMAGEM = 1)
BEGIN
SELECT PS.IDPRODUTOSERVICO, PS.BITIMGPRODUTO
FROM #PRODUTO P INNER JOIN INFM_PRODUTOSERVICO PS ON PS.IDPRODUTOSERVICO = P.IDPRODUTOSERVICO
END