QUERYVALIDACAO SELECT 1 FROM SYS.TABLES AS T JOIN SYS.COLUMNS AS C ON T.OBJECT_ID = C.OBJECT_ID WHERE T.TYPE = 'U' AND T.NAME = 'INFM_ITEMVENDA' AND C.NAME = 'CODESTADO'
BANCODEDADOS IGERENCE
ALTER TABLE INFM_ITEMVENDA ADD CODESTADO CODIGO20 NOT NULL