QUERYVALIDACAO select 1 FROM INFM_PERMISSAO WHERE CODPERMISSAO = 'GUARDARESTOQUEATUAL'
BANCODEDADOS IGERENCE
INSERT INTO INFM_PERMISSAO
           (IDPERMISSAO
           ,CODPERMISSAO
           ,DESPERMISSAO
		   ,BOLOBRIGATORIA)
     VALUES
           (NEWID()
           ,'GUARDARESTOQUEATUAL'
           ,'Tela para Configurar Estoque Atual'
		   ,0)