QUERYVALIDACAO select 1 from sys.sysobjects o  where o.name = 'SP_ATUALIZARESTOQUECOMPRA'
BANCODEDADOS IGERENCE
CREATE PROCEDURE [dbo].[SP_ATUALIZARESTOQUECOMPRA] @IDPRODUTOFILIAL VARCHAR(36),
												   @QUANTIDADE DECIMAL(10,3)
AS

DECLARE @IDDATOSCOMPRAPROD AS VARCHAR(36)
DECLARE @NUMESTOQUECOMPRA AS DECIMAL(10,3)
DECLARE @DTHVALIDADE AS DATETIME
DECLARE @NUMESTOQUEREMANECENTE DECIMAL(10,3)
DECLARE @TEXTO AS VARCHAR(MAX)

SELECT @IDDATOSCOMPRAPROD = IDDATOSCOMPRAPROD,
	   @NUMESTOQUECOMPRA = NUMESTOQUE
FROM INFM_DATOSCOMPRAPROD
WHERE IDPRODUTOFILIAL = @IDPRODUTOFILIAL AND BOLESTOQUEATUAL = 1

IF(@NUMESTOQUECOMPRA = @QUANTIDADE)
	BEGIN
		 UPDATE INFM_DATOSCOMPRAPROD
		 SET
		 NUMESTOQUE = 0,
		 BOLESTOQUEATUAL = 0
		 WHERE
		 IDDATOSCOMPRAPROD = @IDDATOSCOMPRAPROD

		SELECT @DTHVALIDADE = MIN(DTHVALIDADE)
		FROM INFM_DATOSCOMPRAPROD
		WHERE IDPRODUTOFILIAL = @IDPRODUTOFILIAL

		IF @DTHVALIDADE IS NOT NULL	
			UPDATE INFM_DATOSCOMPRAPROD
			SET
			BOLESTOQUEATUAL = 1
			WHERE
			IDPRODUTOFILIAL = @IDPRODUTOFILIAL AND DTHVALIDADE = @DTHVALIDADE
		ELSE
		THROW 99001, 'Não está sendo encontrado compras com data de validade para atualizar o estoque', 1;
	END
ELSE IF @NUMESTOQUECOMPRA > @QUANTIDADE
	BEGIN
			UPDATE INFM_DATOSCOMPRAPROD
			SET
			NUMESTOQUE = (@NUMESTOQUECOMPRA - @QUANTIDADE),
			BOLESTOQUEATUAL = 1
			WHERE
			IDDATOSCOMPRAPROD = @IDDATOSCOMPRAPROD
	END

ELSE
        
         UPDATE INFM_DATOSCOMPRAPROD
		 SET
		 NUMESTOQUE = 0,
		 BOLESTOQUEATUAL = 0
		 WHERE
		 IDDATOSCOMPRAPROD = @IDDATOSCOMPRAPROD

		 SET @NUMESTOQUEREMANECENTE = (@QUANTIDADE - @NUMESTOQUECOMPRA)

		SELECT @DTHVALIDADE = MIN(DTHVALIDADE)
		FROM INFM_DATOSCOMPRAPROD
		WHERE IDPRODUTOFILIAL = @IDPRODUTOFILIAL AND NUMESTOQUE > 0

		IF @DTHVALIDADE IS NOT NULL
		BEGIN
		 
			SELECT @IDDATOSCOMPRAPROD = IDDATOSCOMPRAPROD,
				   @NUMESTOQUECOMPRA = NUMESTOQUE
			FROM INFM_DATOSCOMPRAPROD
			WHERE			
			IDPRODUTOFILIAL = @IDPRODUTOFILIAL AND DTHVALIDADE = @DTHVALIDADE AND NUMESTOQUE > 0

			IF @NUMESTOQUECOMPRA > @NUMESTOQUEREMANECENTE
				UPDATE INFM_DATOSCOMPRAPROD 
				SET
				BOLESTOQUEATUAL = 1,
				NUMESTOQUE = (@NUMESTOQUECOMPRA - @NUMESTOQUEREMANECENTE)
				WHERE IDDATOSCOMPRAPROD = @IDDATOSCOMPRAPROD
			ELSE
			  BEGIN
			   UPDATE INFM_DATOSCOMPRAPROD
			   SET
			   BOLESTOQUEATUAL = 1
			   WHERE 
			   IDDATOSCOMPRAPROD = @IDDATOSCOMPRAPROD
			   EXEC SP_ATUALIZARESTOQUECOMPRA @IDPRODUTOFILIAL, @NUMESTOQUEREMANECENTE
			  END;
		END	 
		ELSE
		THROW 99001, 'Não está sendo encontrado compras com data de validade para atualizar o estoque', 1;