QUERYVALIDACAO select 1 FROM INFM_PARAMETROOPCAO WHERE CODPARAMETROOPCAO = '6POSICOES'
BANCODEDADOS IGERENCE
INSERT INTO INFM_PARAMETROOPCAO
           (IDPARAMETROOPCAO
           ,IDPARAMETRO
           ,CODPARAMETROOPCAO
           ,DESPARAMETROOPCAO)
     VALUES
           (NEWID()
           ,(SELECT IDPARAMETRO FROM INFM_PARAMETROS WHERE CODPARAMETRO = 'TipoCodigoBarras')
           ,'6POSICOES'
           ,'6 POSIÇÕES')