QUERYVALIDACAO SELECT 1 FROM SYS.TABLES AS T JOIN SYS.COLUMNS AS C ON T.OBJECT_ID = C.OBJECT_ID WHERE T.TYPE = 'U' AND T.NAME = 'INFM_ITEMVENDAACRESCIMO' AND C.NAME = 'NUMQUANTIDADE'
BANCODEDADOS IGERENCE
ALTER TABLE INFM_ITEMVENDAACRESCIMO ADD NUMQUANTIDADE NUMERO_DECIMAL_10_3 not null