QUERYVALIDACAO select 1 FROM INFM_PERMISSAOACAO PA INNER JOIN INFM_PERMISSAO P ON P.IDPERMISSAO = PA.IDPERMISSAO WHERE P.CODPERMISSAO = 'MESA' AND IDACAO = '3'
BANCODEDADOS IGERENCE
INSERT INTO INFM_PERMISSAOACAO
           (IDPERMISSAOACAO
           ,IDPERMISSAO
           ,IDACAO)
     VALUES
           (NEWID()
           ,(SELECT IDPERMISSAO FROM INFM_PERMISSAO WHERE CODPERMISSAO = 'MESA')
           ,'3')