QUERYVALIDACAO SELECT 1 FROM SYS.TABLES AS T JOIN SYS.COLUMNS AS C ON T.OBJECT_ID = C.OBJECT_ID WHERE T.TYPE = 'U' AND T.NAME = 'INFM_ITEMPROCESSOERRO' AND C.NAME = 'IDPROCESSO'
BANCODEDADOS IGERENCE
ALTER TABLE INFM_ITEMPROCESSOERRO ADD IDPROCESSO OBJETO_ID not null